lang: en
title: Open Sales and Distribution Model
tagline: OSDM
email: andreas.schlapbach@sbb.ch

description: >- # this means to ignore newlines until "baseurl:"
  Open Sales and Distribution Model to simplify rail distribution.

baseurl: "/" # the subpath of your site, e.g. /blog

# url: "http://osdm.github.com"

permalink: pretty

favicon: favicon.png

fixed_navbar: top

# Build settings
remote_theme: chrisrhymes/bulma-clean-theme@v1.0.0

force_theme: light

# Don't publish posts in the future
future: false

# Measuring hits
google-analytics: UA-185392233-1

paginate: 3
paginate_path: "/blog/page:num"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  - kramdown-parser-gfm

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

markdown: kramdown
