/**
 */
package Gtm.provider;

import Gtm.GtmPackage;
import Gtm.util.GtmAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import java.util.List;
import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.util.ResourceLocator;
import org.eclipse.emf.edit.domain.EditingDomain;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ChildCreationExtenderManager;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IChildCreationExtender;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class GtmItemProviderAdapterFactory extends GtmAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable, IChildCreationExtender {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This helps manage the child creation extenders.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChildCreationExtenderManager childCreationExtenderManager = new ChildCreationExtenderManager(GtmEditPlugin.INSTANCE, GtmPackage.eNS_URI);

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public GtmItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.GTMTool} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GTMToolItemProvider gtmToolItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.GTMTool}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGTMToolAdapter() {
		if (gtmToolItemProvider == null) {
			gtmToolItemProvider = new GTMToolItemProvider(this);
		}

		return gtmToolItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.CodeLists} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CodeListsItemProvider codeListsItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.CodeLists}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCodeListsAdapter() {
		if (codeListsItemProvider == null) {
			codeListsItemProvider = new CodeListsItemProvider(this);
		}

		return codeListsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.GeneralTariffModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GeneralTariffModelItemProvider generalTariffModelItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.GeneralTariffModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGeneralTariffModelAdapter() {
		if (generalTariffModelItemProvider == null) {
			generalTariffModelItemProvider = new GeneralTariffModelItemProvider(this);
		}

		return generalTariffModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.ConversionFromLegacy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConversionFromLegacyItemProvider conversionFromLegacyItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.ConversionFromLegacy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConversionFromLegacyAdapter() {
		if (conversionFromLegacyItemProvider == null) {
			conversionFromLegacyItemProvider = new ConversionFromLegacyItemProvider(this);
		}

		return conversionFromLegacyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.FareStructure} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FareStructureItemProvider fareStructureItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.FareStructure}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFareStructureAdapter() {
		if (fareStructureItemProvider == null) {
			fareStructureItemProvider = new FareStructureItemProvider(this);
		}

		return fareStructureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.Delivery} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeliveryItemProvider deliveryItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.Delivery}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeliveryAdapter() {
		if (deliveryItemProvider == null) {
			deliveryItemProvider = new DeliveryItemProvider(this);
		}

		return deliveryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.BorderPoints} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BorderPointsItemProvider borderPointsItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.BorderPoints}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBorderPointsAdapter() {
		if (borderPointsItemProvider == null) {
			borderPointsItemProvider = new BorderPointsItemProvider(this);
		}

		return borderPointsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.Calendar} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CalendarItemProvider calendarItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.Calendar}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCalendarAdapter() {
		if (calendarItemProvider == null) {
			calendarItemProvider = new CalendarItemProvider(this);
		}

		return calendarItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.Carrier} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CarrierItemProvider carrierItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.Carrier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCarrierAdapter() {
		if (carrierItemProvider == null) {
			carrierItemProvider = new CarrierItemProvider(this);
		}

		return carrierItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.CoversionParams} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CoversionParamsItemProvider coversionParamsItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.CoversionParams}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCoversionParamsAdapter() {
		if (coversionParamsItemProvider == null) {
			coversionParamsItemProvider = new CoversionParamsItemProvider(this);
		}

		return coversionParamsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.LegacyDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LegacyDescriptionItemProvider legacyDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.LegacyDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLegacyDescriptionAdapter() {
		if (legacyDescriptionItemProvider == null) {
			legacyDescriptionItemProvider = new LegacyDescriptionItemProvider(this);
		}

		return legacyDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.LegacyDistanceFare} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LegacyDistanceFareItemProvider legacyDistanceFareItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.LegacyDistanceFare}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLegacyDistanceFareAdapter() {
		if (legacyDistanceFareItemProvider == null) {
			legacyDistanceFareItemProvider = new LegacyDistanceFareItemProvider(this);
		}

		return legacyDistanceFareItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.LegacyFares} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LegacyFaresItemProvider legacyFaresItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.LegacyFares}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLegacyFaresAdapter() {
		if (legacyFaresItemProvider == null) {
			legacyFaresItemProvider = new LegacyFaresItemProvider(this);
		}

		return legacyFaresItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.Legacy108} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Legacy108ItemProvider legacy108ItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.Legacy108}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLegacy108Adapter() {
		if (legacy108ItemProvider == null) {
			legacy108ItemProvider = new Legacy108ItemProvider(this);
		}

		return legacy108ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.LegacyRouteFare} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LegacyRouteFareItemProvider legacyRouteFareItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.LegacyRouteFare}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLegacyRouteFareAdapter() {
		if (legacyRouteFareItemProvider == null) {
			legacyRouteFareItemProvider = new LegacyRouteFareItemProvider(this);
		}

		return legacyRouteFareItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.LegacySeries} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LegacySeriesItemProvider legacySeriesItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.LegacySeries}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLegacySeriesAdapter() {
		if (legacySeriesItemProvider == null) {
			legacySeriesItemProvider = new LegacySeriesItemProvider(this);
		}

		return legacySeriesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.LegacyViastation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LegacyViastationItemProvider legacyViastationItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.LegacyViastation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLegacyViastationAdapter() {
		if (legacyViastationItemProvider == null) {
			legacyViastationItemProvider = new LegacyViastationItemProvider(this);
		}

		return legacyViastationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.LegacyStationMap} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LegacyStationMapItemProvider legacyStationMapItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.LegacyStationMap}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLegacyStationMapAdapter() {
		if (legacyStationMapItemProvider == null) {
			legacyStationMapItemProvider = new LegacyStationMapItemProvider(this);
		}

		return legacyStationMapItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.StationsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StationsTypeItemProvider stationsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.StationsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStationsTypeAdapter() {
		if (stationsTypeItemProvider == null) {
			stationsTypeItemProvider = new StationsTypeItemProvider(this);
		}

		return stationsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.TargetFareTemplate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TargetFareTemplateItemProvider targetFareTemplateItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.TargetFareTemplate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTargetFareTemplateAdapter() {
		if (targetFareTemplateItemProvider == null) {
			targetFareTemplateItemProvider = new TargetFareTemplateItemProvider(this);
		}

		return targetFareTemplateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.Station} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StationItemProvider stationItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.Station}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStationAdapter() {
		if (stationItemProvider == null) {
			stationItemProvider = new StationItemProvider(this);
		}

		return stationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.Country} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CountryItemProvider countryItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.Country}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCountryAdapter() {
		if (countryItemProvider == null) {
			countryItemProvider = new CountryItemProvider(this);
		}

		return countryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.Language} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LanguageItemProvider languageItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.Language}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLanguageAdapter() {
		if (languageItemProvider == null) {
			languageItemProvider = new LanguageItemProvider(this);
		}

		return languageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.Text} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextItemProvider textItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.Text}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTextAdapter() {
		if (textItemProvider == null) {
			textItemProvider = new TextItemProvider(this);
		}

		return textItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.Translation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TranslationItemProvider translationItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.Translation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTranslationAdapter() {
		if (translationItemProvider == null) {
			translationItemProvider = new TranslationItemProvider(this);
		}

		return translationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.ServiceClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceClassItemProvider serviceClassItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.ServiceClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceClassAdapter() {
		if (serviceClassItemProvider == null) {
			serviceClassItemProvider = new ServiceClassItemProvider(this);
		}

		return serviceClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.ServiceLevel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceLevelItemProvider serviceLevelItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.ServiceLevel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceLevelAdapter() {
		if (serviceLevelItemProvider == null) {
			serviceLevelItemProvider = new ServiceLevelItemProvider(this);
		}

		return serviceLevelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.Price} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PriceItemProvider priceItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.Price}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPriceAdapter() {
		if (priceItemProvider == null) {
			priceItemProvider = new PriceItemProvider(this);
		}

		return priceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.ReservationParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReservationParameterItemProvider reservationParameterItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.ReservationParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReservationParameterAdapter() {
		if (reservationParameterItemProvider == null) {
			reservationParameterItemProvider = new ReservationParameterItemProvider(this);
		}

		return reservationParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.ReservationParams9181} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReservationParams9181ItemProvider reservationParams9181ItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.ReservationParams9181}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReservationParams9181Adapter() {
		if (reservationParams9181ItemProvider == null) {
			reservationParams9181ItemProvider = new ReservationParams9181ItemProvider(this);
		}

		return reservationParams9181ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.ReservationOptions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReservationOptionsItemProvider reservationOptionsItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.ReservationOptions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReservationOptionsAdapter() {
		if (reservationOptionsItemProvider == null) {
			reservationOptionsItemProvider = new ReservationOptionsItemProvider(this);
		}

		return reservationOptionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.ReservationPreference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReservationPreferenceItemProvider reservationPreferenceItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.ReservationPreference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReservationPreferenceAdapter() {
		if (reservationPreferenceItemProvider == null) {
			reservationPreferenceItemProvider = new ReservationPreferenceItemProvider(this);
		}

		return reservationPreferenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.CurrencyPrice} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CurrencyPriceItemProvider currencyPriceItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.CurrencyPrice}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCurrencyPriceAdapter() {
		if (currencyPriceItemProvider == null) {
			currencyPriceItemProvider = new CurrencyPriceItemProvider(this);
		}

		return currencyPriceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.Currency} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CurrencyItemProvider currencyItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.Currency}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCurrencyAdapter() {
		if (currencyItemProvider == null) {
			currencyItemProvider = new CurrencyItemProvider(this);
		}

		return currencyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.VATDetail} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VATDetailItemProvider vatDetailItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.VATDetail}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVATDetailAdapter() {
		if (vatDetailItemProvider == null) {
			vatDetailItemProvider = new VATDetailItemProvider(this);
		}

		return vatDetailItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.RegionalConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RegionalConstraintItemProvider regionalConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.RegionalConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRegionalConstraintAdapter() {
		if (regionalConstraintItemProvider == null) {
			regionalConstraintItemProvider = new RegionalConstraintItemProvider(this);
		}

		return regionalConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.ConnectionPoint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConnectionPointItemProvider connectionPointItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.ConnectionPoint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConnectionPointAdapter() {
		if (connectionPointItemProvider == null) {
			connectionPointItemProvider = new ConnectionPointItemProvider(this);
		}

		return connectionPointItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.ServiceConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceConstraintItemProvider serviceConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.ServiceConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceConstraintAdapter() {
		if (serviceConstraintItemProvider == null) {
			serviceConstraintItemProvider = new ServiceConstraintItemProvider(this);
		}

		return serviceConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.CarrierConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CarrierConstraintItemProvider carrierConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.CarrierConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCarrierConstraintAdapter() {
		if (carrierConstraintItemProvider == null) {
			carrierConstraintItemProvider = new CarrierConstraintItemProvider(this);
		}

		return carrierConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.FareElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FareElementItemProvider fareElementItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.FareElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFareElementAdapter() {
		if (fareElementItemProvider == null) {
			fareElementItemProvider = new FareElementItemProvider(this);
		}

		return fareElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.ReductionCard} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReductionCardItemProvider reductionCardItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.ReductionCard}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReductionCardAdapter() {
		if (reductionCardItemProvider == null) {
			reductionCardItemProvider = new ReductionCardItemProvider(this);
		}

		return reductionCardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.ServiceBrand} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceBrandItemProvider serviceBrandItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.ServiceBrand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceBrandAdapter() {
		if (serviceBrandItemProvider == null) {
			serviceBrandItemProvider = new ServiceBrandItemProvider(this);
		}

		return serviceBrandItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.SalesAvailabilityConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SalesAvailabilityConstraintItemProvider salesAvailabilityConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.SalesAvailabilityConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSalesAvailabilityConstraintAdapter() {
		if (salesAvailabilityConstraintItemProvider == null) {
			salesAvailabilityConstraintItemProvider = new SalesAvailabilityConstraintItemProvider(this);
		}

		return salesAvailabilityConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.TravelValidityConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TravelValidityConstraintItemProvider travelValidityConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.TravelValidityConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTravelValidityConstraintAdapter() {
		if (travelValidityConstraintItemProvider == null) {
			travelValidityConstraintItemProvider = new TravelValidityConstraintItemProvider(this);
		}

		return travelValidityConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.SalesRestriction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SalesRestrictionItemProvider salesRestrictionItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.SalesRestriction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSalesRestrictionAdapter() {
		if (salesRestrictionItemProvider == null) {
			salesRestrictionItemProvider = new SalesRestrictionItemProvider(this);
		}

		return salesRestrictionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.TimeReference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TimeReferenceItemProvider timeReferenceItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.TimeReference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTimeReferenceAdapter() {
		if (timeReferenceItemProvider == null) {
			timeReferenceItemProvider = new TimeReferenceItemProvider(this);
		}

		return timeReferenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.CombinationConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CombinationConstraintItemProvider combinationConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.CombinationConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCombinationConstraintAdapter() {
		if (combinationConstraintItemProvider == null) {
			combinationConstraintItemProvider = new CombinationConstraintItemProvider(this);
		}

		return combinationConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.ValidityRange} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ValidityRangeItemProvider validityRangeItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.ValidityRange}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createValidityRangeAdapter() {
		if (validityRangeItemProvider == null) {
			validityRangeItemProvider = new ValidityRangeItemProvider(this);
		}

		return validityRangeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.TimeRange} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TimeRangeItemProvider timeRangeItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.TimeRange}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTimeRangeAdapter() {
		if (timeRangeItemProvider == null) {
			timeRangeItemProvider = new TimeRangeItemProvider(this);
		}

		return timeRangeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.ReturnValidityConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReturnValidityConstraintItemProvider returnValidityConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.ReturnValidityConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReturnValidityConstraintAdapter() {
		if (returnValidityConstraintItemProvider == null) {
			returnValidityConstraintItemProvider = new ReturnValidityConstraintItemProvider(this);
		}

		return returnValidityConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.FareCombinationModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FareCombinationModelItemProvider fareCombinationModelItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.FareCombinationModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFareCombinationModelAdapter() {
		if (fareCombinationModelItemProvider == null) {
			fareCombinationModelItemProvider = new FareCombinationModelItemProvider(this);
		}

		return fareCombinationModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.RegionalValidity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RegionalValidityItemProvider regionalValidityItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.RegionalValidity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRegionalValidityAdapter() {
		if (regionalValidityItemProvider == null) {
			regionalValidityItemProvider = new RegionalValidityItemProvider(this);
		}

		return regionalValidityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.ViaStation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ViaStationItemProvider viaStationItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.ViaStation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createViaStationAdapter() {
		if (viaStationItemProvider == null) {
			viaStationItemProvider = new ViaStationItemProvider(this);
		}

		return viaStationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.Zone} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ZoneItemProvider zoneItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.Zone}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createZoneAdapter() {
		if (zoneItemProvider == null) {
			zoneItemProvider = new ZoneItemProvider(this);
		}

		return zoneItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.NutsCode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NutsCodeItemProvider nutsCodeItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.NutsCode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNutsCodeAdapter() {
		if (nutsCodeItemProvider == null) {
			nutsCodeItemProvider = new NutsCodeItemProvider(this);
		}

		return nutsCodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.Line} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LineItemProvider lineItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.Line}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLineAdapter() {
		if (lineItemProvider == null) {
			lineItemProvider = new LineItemProvider(this);
		}

		return lineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.Polygone} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PolygoneItemProvider polygoneItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.Polygone}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPolygoneAdapter() {
		if (polygoneItemProvider == null) {
			polygoneItemProvider = new PolygoneItemProvider(this);
		}

		return polygoneItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.Edge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EdgeItemProvider edgeItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.Edge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEdgeAdapter() {
		if (edgeItemProvider == null) {
			edgeItemProvider = new EdgeItemProvider(this);
		}

		return edgeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.PassengerConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PassengerConstraintItemProvider passengerConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.PassengerConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPassengerConstraintAdapter() {
		if (passengerConstraintItemProvider == null) {
			passengerConstraintItemProvider = new PassengerConstraintItemProvider(this);
		}

		return passengerConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.PassengerCombinationConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PassengerCombinationConstraintItemProvider passengerCombinationConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.PassengerCombinationConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPassengerCombinationConstraintAdapter() {
		if (passengerCombinationConstraintItemProvider == null) {
			passengerCombinationConstraintItemProvider = new PassengerCombinationConstraintItemProvider(this);
		}

		return passengerCombinationConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.RelativeTime} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelativeTimeItemProvider relativeTimeItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.RelativeTime}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelativeTimeAdapter() {
		if (relativeTimeItemProvider == null) {
			relativeTimeItemProvider = new RelativeTimeItemProvider(this);
		}

		return relativeTimeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.ZoneDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ZoneDefinitionItemProvider zoneDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.ZoneDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createZoneDefinitionAdapter() {
		if (zoneDefinitionItemProvider == null) {
			zoneDefinitionItemProvider = new ZoneDefinitionItemProvider(this);
		}

		return zoneDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.AfterSalesCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AfterSalesConditionItemProvider afterSalesConditionItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.AfterSalesCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAfterSalesConditionAdapter() {
		if (afterSalesConditionItemProvider == null) {
			afterSalesConditionItemProvider = new AfterSalesConditionItemProvider(this);
		}

		return afterSalesConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.AfterSalesRule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AfterSalesRuleItemProvider afterSalesRuleItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.AfterSalesRule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAfterSalesRuleAdapter() {
		if (afterSalesRuleItemProvider == null) {
			afterSalesRuleItemProvider = new AfterSalesRuleItemProvider(this);
		}

		return afterSalesRuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.PersonalDataConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PersonalDataConstraintItemProvider personalDataConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.PersonalDataConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPersonalDataConstraintAdapter() {
		if (personalDataConstraintItemProvider == null) {
			personalDataConstraintItemProvider = new PersonalDataConstraintItemProvider(this);
		}

		return personalDataConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.RequiredPersonalData} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RequiredPersonalDataItemProvider requiredPersonalDataItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.RequiredPersonalData}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRequiredPersonalDataAdapter() {
		if (requiredPersonalDataItemProvider == null) {
			requiredPersonalDataItemProvider = new RequiredPersonalDataItemProvider(this);
		}

		return requiredPersonalDataItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.CrossBorderCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CrossBorderConditionItemProvider crossBorderConditionItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.CrossBorderCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCrossBorderConditionAdapter() {
		if (crossBorderConditionItemProvider == null) {
			crossBorderConditionItemProvider = new CrossBorderConditionItemProvider(this);
		}

		return crossBorderConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.AllowedPersonalDataChanges} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AllowedPersonalDataChangesItemProvider allowedPersonalDataChangesItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.AllowedPersonalDataChanges}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAllowedPersonalDataChangesAdapter() {
		if (allowedPersonalDataChangesItemProvider == null) {
			allowedPersonalDataChangesItemProvider = new AllowedPersonalDataChangesItemProvider(this);
		}

		return allowedPersonalDataChangesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.ReductionConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReductionConstraintItemProvider reductionConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.ReductionConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReductionConstraintAdapter() {
		if (reductionConstraintItemProvider == null) {
			reductionConstraintItemProvider = new ReductionConstraintItemProvider(this);
		}

		return reductionConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.RequiredReductionCard} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RequiredReductionCardItemProvider requiredReductionCardItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.RequiredReductionCard}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRequiredReductionCardAdapter() {
		if (requiredReductionCardItemProvider == null) {
			requiredReductionCardItemProvider = new RequiredReductionCardItemProvider(this);
		}

		return requiredReductionCardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.FulfillmentConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FulfillmentConstraintItemProvider fulfillmentConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.FulfillmentConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFulfillmentConstraintAdapter() {
		if (fulfillmentConstraintItemProvider == null) {
			fulfillmentConstraintItemProvider = new FulfillmentConstraintItemProvider(this);
		}

		return fulfillmentConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.FareResourceLocation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FareResourceLocationItemProvider fareResourceLocationItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.FareResourceLocation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFareResourceLocationAdapter() {
		if (fareResourceLocationItemProvider == null) {
			fareResourceLocationItemProvider = new FareResourceLocationItemProvider(this);
		}

		return fareResourceLocationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.TrainResourceLocation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TrainResourceLocationItemProvider trainResourceLocationItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.TrainResourceLocation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTrainResourceLocationAdapter() {
		if (trainResourceLocationItemProvider == null) {
			trainResourceLocationItemProvider = new TrainResourceLocationItemProvider(this);
		}

		return trainResourceLocationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.CarrierResourceLocation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CarrierResourceLocationItemProvider carrierResourceLocationItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.CarrierResourceLocation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCarrierResourceLocationAdapter() {
		if (carrierResourceLocationItemProvider == null) {
			carrierResourceLocationItemProvider = new CarrierResourceLocationItemProvider(this);
		}

		return carrierResourceLocationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.StationResourceLocation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StationResourceLocationItemProvider stationResourceLocationItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.StationResourceLocation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStationResourceLocationAdapter() {
		if (stationResourceLocationItemProvider == null) {
			stationResourceLocationItemProvider = new StationResourceLocationItemProvider(this);
		}

		return stationResourceLocationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Gtm.OnlineResource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OnlineResourceItemProvider onlineResourceItemProvider;

	/**
	 * This creates an adapter for a {@link Gtm.OnlineResource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOnlineResourceAdapter() {
		if (onlineResourceItemProvider == null) {
			onlineResourceItemProvider = new OnlineResourceItemProvider(this);
		}

		return onlineResourceItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public List<IChildCreationExtender> getChildCreationExtenders() {
		return childCreationExtenderManager.getChildCreationExtenders();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Collection<?> getNewChildDescriptors(Object object, EditingDomain editingDomain) {
		return childCreationExtenderManager.getNewChildDescriptors(object, editingDomain);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ResourceLocator getResourceLocator() {
		return childCreationExtenderManager;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (gtmToolItemProvider != null) gtmToolItemProvider.dispose();
		if (codeListsItemProvider != null) codeListsItemProvider.dispose();
		if (generalTariffModelItemProvider != null) generalTariffModelItemProvider.dispose();
		if (conversionFromLegacyItemProvider != null) conversionFromLegacyItemProvider.dispose();
		if (fareStructureItemProvider != null) fareStructureItemProvider.dispose();
		if (deliveryItemProvider != null) deliveryItemProvider.dispose();
		if (borderPointsItemProvider != null) borderPointsItemProvider.dispose();
		if (calendarItemProvider != null) calendarItemProvider.dispose();
		if (carrierItemProvider != null) carrierItemProvider.dispose();
		if (coversionParamsItemProvider != null) coversionParamsItemProvider.dispose();
		if (legacyDescriptionItemProvider != null) legacyDescriptionItemProvider.dispose();
		if (legacyDistanceFareItemProvider != null) legacyDistanceFareItemProvider.dispose();
		if (legacyFaresItemProvider != null) legacyFaresItemProvider.dispose();
		if (legacy108ItemProvider != null) legacy108ItemProvider.dispose();
		if (legacyRouteFareItemProvider != null) legacyRouteFareItemProvider.dispose();
		if (legacySeriesItemProvider != null) legacySeriesItemProvider.dispose();
		if (legacyViastationItemProvider != null) legacyViastationItemProvider.dispose();
		if (legacyStationMapItemProvider != null) legacyStationMapItemProvider.dispose();
		if (carrierConstraintItemProvider != null) carrierConstraintItemProvider.dispose();
		if (countryItemProvider != null) countryItemProvider.dispose();
		if (connectionPointItemProvider != null) connectionPointItemProvider.dispose();
		if (currencyItemProvider != null) currencyItemProvider.dispose();
		if (currencyPriceItemProvider != null) currencyPriceItemProvider.dispose();
		if (languageItemProvider != null) languageItemProvider.dispose();
		if (priceItemProvider != null) priceItemProvider.dispose();
		if (reductionCardItemProvider != null) reductionCardItemProvider.dispose();
		if (regionalConstraintItemProvider != null) regionalConstraintItemProvider.dispose();
		if (reservationParameterItemProvider != null) reservationParameterItemProvider.dispose();
		if (reservationParams9181ItemProvider != null) reservationParams9181ItemProvider.dispose();
		if (reservationOptionsItemProvider != null) reservationOptionsItemProvider.dispose();
		if (reservationPreferenceItemProvider != null) reservationPreferenceItemProvider.dispose();
		if (serviceClassItemProvider != null) serviceClassItemProvider.dispose();
		if (serviceLevelItemProvider != null) serviceLevelItemProvider.dispose();
		if (serviceConstraintItemProvider != null) serviceConstraintItemProvider.dispose();
		if (stationItemProvider != null) stationItemProvider.dispose();
		if (stationsTypeItemProvider != null) stationsTypeItemProvider.dispose();
		if (targetFareTemplateItemProvider != null) targetFareTemplateItemProvider.dispose();
		if (travelValidityConstraintItemProvider != null) travelValidityConstraintItemProvider.dispose();
		if (textItemProvider != null) textItemProvider.dispose();
		if (translationItemProvider != null) translationItemProvider.dispose();
		if (vatDetailItemProvider != null) vatDetailItemProvider.dispose();
		if (fareElementItemProvider != null) fareElementItemProvider.dispose();
		if (serviceBrandItemProvider != null) serviceBrandItemProvider.dispose();
		if (salesAvailabilityConstraintItemProvider != null) salesAvailabilityConstraintItemProvider.dispose();
		if (salesRestrictionItemProvider != null) salesRestrictionItemProvider.dispose();
		if (timeReferenceItemProvider != null) timeReferenceItemProvider.dispose();
		if (combinationConstraintItemProvider != null) combinationConstraintItemProvider.dispose();
		if (validityRangeItemProvider != null) validityRangeItemProvider.dispose();
		if (timeRangeItemProvider != null) timeRangeItemProvider.dispose();
		if (returnValidityConstraintItemProvider != null) returnValidityConstraintItemProvider.dispose();
		if (fareCombinationModelItemProvider != null) fareCombinationModelItemProvider.dispose();
		if (regionalValidityItemProvider != null) regionalValidityItemProvider.dispose();
		if (viaStationItemProvider != null) viaStationItemProvider.dispose();
		if (zoneItemProvider != null) zoneItemProvider.dispose();
		if (nutsCodeItemProvider != null) nutsCodeItemProvider.dispose();
		if (lineItemProvider != null) lineItemProvider.dispose();
		if (polygoneItemProvider != null) polygoneItemProvider.dispose();
		if (edgeItemProvider != null) edgeItemProvider.dispose();
		if (passengerConstraintItemProvider != null) passengerConstraintItemProvider.dispose();
		if (passengerCombinationConstraintItemProvider != null) passengerCombinationConstraintItemProvider.dispose();
		if (relativeTimeItemProvider != null) relativeTimeItemProvider.dispose();
		if (zoneDefinitionItemProvider != null) zoneDefinitionItemProvider.dispose();
		if (afterSalesConditionItemProvider != null) afterSalesConditionItemProvider.dispose();
		if (afterSalesRuleItemProvider != null) afterSalesRuleItemProvider.dispose();
		if (personalDataConstraintItemProvider != null) personalDataConstraintItemProvider.dispose();
		if (requiredPersonalDataItemProvider != null) requiredPersonalDataItemProvider.dispose();
		if (crossBorderConditionItemProvider != null) crossBorderConditionItemProvider.dispose();
		if (allowedPersonalDataChangesItemProvider != null) allowedPersonalDataChangesItemProvider.dispose();
		if (reductionConstraintItemProvider != null) reductionConstraintItemProvider.dispose();
		if (requiredReductionCardItemProvider != null) requiredReductionCardItemProvider.dispose();
		if (fulfillmentConstraintItemProvider != null) fulfillmentConstraintItemProvider.dispose();
		if (fareResourceLocationItemProvider != null) fareResourceLocationItemProvider.dispose();
		if (trainResourceLocationItemProvider != null) trainResourceLocationItemProvider.dispose();
		if (carrierResourceLocationItemProvider != null) carrierResourceLocationItemProvider.dispose();
		if (stationResourceLocationItemProvider != null) stationResourceLocationItemProvider.dispose();
		if (onlineResourceItemProvider != null) onlineResourceItemProvider.dispose();
	}

}
