openapi: 3.1.0
servers:
  - description: No server provided
    url: /
info:
  title: UIC 90918-10 - OSDM webhooks
  version: 4.0.0
  description: |
    Specifications for the OSDM API standard. The OSDM webhook specification allows an
    allocator to inform a distributor about changes to a booking or a complaint.
  contact:
    name: OSDM Working Group
    url: "https://osdm.io"
    email: osdm@uic.org
  license:
    name: Apache 2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"

tags:
  - name: Events
    description: Webhook event notifications from allocator to distributor.

security:
  - oAuth2ClientCredentials: []

webhooks:
  events:
    post:
      summary: Event occured
      description: An event has occurred
      tags:
        - Events
      operationId: postEvent
      requestBody:
        description: Information about the event
        content:
          application/json:
            schema:
              oneOf:
                - $ref: ./schemas/booking.yml#/BookingEvent
                - $ref: ./schemas/complaint.yml#/ComplaintEvent
                - $ref: ./schemas/complaint.yml#/ReimbursementEvent
      responses:
        "200":
          description: OK
        "400":
          description: bad input parameter
        "401":
          description: unauthorized
        "403":
          description: forbidden
        "404":
          description: no place information found
        "500":
          description: internal server error
        "501":
          description: not implemented
        "503":
          description: service unavailable

components:
  securitySchemes:
    oAuth2ClientCredentials:
      $ref: ./components/security-schemes.yml#/oAuth2ClientCredentials
