FacilityEnum:
  description: |
    all kinds of Facilities
    COVERED - offers protection from weather
    LIGHTING - is lit
    WHEELCHAIR_ACCESSIBLE - accessible by a wheel chair
  type: string
  x-extendible-enum:
  - GENERIC
  - LIFT
  - ESCALATOR
  - TRAVELATOR
  - RAMP
  - STAIRS
  - SHUTTLE
  - NARROW_ENTRANCE
  - BARRIER
  - PALLET_ACCESS_LOWFLOOR
  - VALIDATOR
  - POLICE
  - FIRST_AID
  - SOS_POINT
  - SPECIFIC_ASSISTANCE
  - UNACCOMPANIED_MINOR_ASSISTANCE
  - BOARDING_ASSISTANCE
  - CAR_HIRE
  - MOTORCYCLE_HIRE
  - CYCLE_HIRE
  - TAXI
  - RECREATION_DEVICE_HIRE
  - BIKE_CARRIAGE
  - BAGGAGE_STORAGE
  - LEFT_LUGGAGE
  - PORTERAGE
  - BAGGAGE_TROLLEYS
  - SUITABLE_FOR_WHEELCHAIRS
  - LOWFLOOR
  - STEP_FREE_ACCESS
  - TACTILE_PLATFORM_EDGES
  - ONBOARD_ASSISTANCE
  - AUDIO_INFORMATION
  - VISUAL_INFORMATION
  - DISPLAYS_FOR_VISUALLY_IMPAIRED
  - AUDIO_FOR_HEARING_IMPAIRED
  - SMOKING
  - NO_SMOKING
  - MOBILEPHONE_USE_ZONE
  - MOBILEPHONE_FREE_ZONE
  - CAR_PARK
  - PARK_AND_RIDE_PARK
  - MOTOR_CYCLE_PARK
  - CYCLE_PARK
  - RENTAL_CAR_PARK
  - COACH_PARK
  - NEXT_STOP_INDICATOR
  - STOP_ANNOUNCEMENTS
  - PASSENGER_INFORMATION_DISPLAY
  - TACTILE_INFORMATION
  - WALKING_GUIDANCE
  - JOURNEY_PLANNING
  - LOST_FOUND
  - INFORMATION_DESK
  - INTERACTIVE_KIOSK_DISPLAY
  - PRINTED_PUBLIC_NOTICE
  - PASSENGER_WIFI
  - TELEPHONE
  - AUDIO_SERVICES
  - VIDEO_SERVICES
  - BUSINESS_SERVICES
  - INTERNET
  - POST_OFFICE
  - LETTER_BOX
  - RESTAURANT_SERVICE
  - SNACKS_SERVICE
  - TROLLEY
  - BAR
  - FOOD_NOT_AVAILABLE
  - BEVERAGES_NOT_AVAILABLE
  - BISTRO
  - FOOD_VENDING_MACHINE
  - BEVERAGE_VENDING_MACHINE
  - LOUNGE
  - HALL
  - MEETING_POINT
  - GROUP_POINT
  - RECEPTION
  - SHELTER
  - SEATS
  - FOOD_RETAILER
  - NEWSPAPER_TOBACCO_RETAILER
  - RECREATION_TRAVEL_RETAILER
  - HYGIENE_HEALTH_BEAUTY_RETAILER
  - FASHION_ACCESSORIES_RETAILER
  - BANK_FINANCE_INSURANCE
  - CASH_MACHINE
  - CURRENCY_EXCHANGE
  - TOURISM_SERVICE
  - PHOTO_BOOTH
  - TOILET
  - NO_TOILET
  - SHOWER
  - WHEELCHAIR_ACCCESS_TOILET
  - BABY_CHANGE
  - TICKET_MACHINES
  - TICKET_OFFICE
  - TICKET_ONDEMAND_MACHINES
  - TICKET_SALES
  - MOBILE_TICKETING
  - TICKET_COLLECTION
  - CENTRAL_RESERVATIONS
  - LOCAL_TICKETS
  - NATIONAL_TICKETS
  - INTERNATIONAL_TICKETS
  - COVERED
  - LIGHTING
  - WHEELCHAIR_ACCESSIBLE
FacilityGroupEnum:
  description: grouping of facilities (provided by OJP)
  type: string
  x-extendible-enum:
  - ACCESS_FACILITY
  - ACCOMMODATION_FACILITY
  - ASSISTANCE_FACILITY
  - HIRE_FACILITY
  - LUGGAGE_FACILITY
  - MOBILITY_FACILITY
  - NUISANCE_FACILITY
  - PARKING_FACILITY
  - PASSENGER_COMMS_FACILITY
  - PASSENGER_INFORMATION_FACILITY
  - REFRESHMENT_FACILITY
  - RESERVED_SPACE_FACILITY
  - RETAIL_FACILITY
  - SANITARY_FACILITY
  - TICKETING_FACILITY
  - STOP_POINT_FACILITY
GeneralAttributeMasterData:
  type: object
  additionalProperties: false
  required:
  - text
  - code
  properties:
    text:
      description: text to be displayed to the user
      $ref: ./_common.yml#/Text
    code:
      type:
      - string
      - 'null'
    key:
      type:
      - string
      - 'null'
    value:
      type:
      - string
      - 'null'
    facilities:
      type: array
      items:
        $ref: ./offer.yml#/GroupedFacilityItem
    mandatory:
      description: true = mandatory to be displayed to the user
      type: boolean
    importance:
      description: importance as percentage
      $ref: ./_common.yml#/Percentage
    _links:
      $ref: ./_common.yml#/Links
MasterDataValidity:
  type: object
  description: "Validity of masterdata. The dates might relate to the sales date or the travel date. It indicates the validity\
    \ of masterdata \nnot the validity of offers, bookings or fulfiullments related to the master data. \nWhen related to\
    \ the sales process on historic data it is related to the createdOn timestamp of the booking part.\nWhen related to the\
    \ travel it indicates the validity of masterdata related to the travel (e.g. product definitions, zone definition). \n\
    The dates related to the trael date must be provided in the offset format.\n"
  required:
  - validFrom
  - validUntil
  properties:
    validFrom:
      description: |
        start of the validity (inclusive)
      type: string
      format: date-time
      examples:
      - '2024-12-31T00:00:00+01:00'
    validUntil:
      description: |
        end of the validity (exclusive)
      type: string
      format: date-time
      examples:
      - '2025-12-31T00:00:00+01:00'
Product:
  type: object
  additionalProperties: false
  description: |
    Structured description of the product, its name, comfort and sales / after-sales conditions
  required:
  - id
  - code
  - owner
  - flexibility
  properties:
    id:
      description: |
        id of the product
      type: string
    summary:
      description: |
        A human-readable description of the product.
      type:
      - string
      - 'null'
    type:
      $ref: '#/ProductType'
    code:
      description: |
        The product code expressed in the provider system (could be a
        mapping from an even lower-level provider).
      type: string
      examples:
      - PT00AD
    description:
      description: |
        Textual description of the product.
      type:
      - string
      - 'null'
    owner:
      $ref: ./_common.yml#/CompanyRef
    conditions:
      description: |
        Structured description of the sales or after-sales conditions.
      type: array
      items:
        $ref: ./_common.yml#/Condition
    flexibility:
      $ref: ./offer.yml#/Flexibility
    serviceClass:
      $ref: ./_common.yml#/ServiceClass
    travelClass:
      $ref: ./_common.yml#/TravelClass
    fulfillmentOptions:
      type: array
      items:
        $ref: ./fulfillment.yml#/FulfillmentOption
    isTrainBound:
      type:
      - boolean
      - 'null'
      default: false
    isReturnProduct:
      type:
      - boolean
      - 'null'
      default: false
    serviceConstraintText:
      type:
      - string
      - 'null'
    carrierConstraintText:
      type:
      - string
      - 'null'
    descriptiveTexts:
      type: array
      items:
        $ref: ./_common.yml#/TextElement
    tariff:
      description: |
        Mapping to Tariff 42 of IRS-90918-3 (Hermes/Hosa). Helps the H2O converter in mapping
        offers to a requested tariff. See legacyReservationParameter.tariff in OSDM offline.
      type:
      - string
      - 'null'
    combinationTags:
      type: array
      items:
        $ref: ./offer.yml#/CombinationTag
    productTags:
      description: product tags associated with the product that can be used to search for offers. This can be omitted outside
        of the product master data service
      type:
      - array
      - 'null'
      items:
        type: string
    _links:
      $ref: ./_common.yml#/Links
ProductCollectionResponse:
  type: object
  additionalProperties: false
  properties:
    problems:
      type: array
      items:
        $ref: ./_common.yml#/Problem
    products:
      description: |
        The list of all products available to the caller.
      type: array
      items:
        $ref: '#/Product'
    _links:
      $ref: ./_common.yml#/Links
ProductResponse:
  type: object
  additionalProperties: false
  properties:
    problems:
      type: array
      items:
        $ref: ./_common.yml#/Problem
    product:
      $ref: '#/Product'
ProductSearchRequest:
  type: object
  additionalProperties: false
  description: |
    Search criteria to search for products
  properties:
    id:
      description: |
        id of the product
      type:
      - string
      - 'null'
    types:
      type: array
      items:
        $ref: '#/ProductType'
    codes:
      description: |
        The product codees to be searched.
      type: array
      items:
        type: string
    flexibilities:
      type: array
      items:
        $ref: ./offer.yml#/Flexibility
    serviceClasses:
      type: array
      items:
        $ref: ./_common.yml#/ServiceClass
    travelClasses:
      type: array
      items:
        $ref: ./_common.yml#/TravelClass
    fulfillmentOptions:
      type: array
      items:
        $ref: ./fulfillment.yml#/FulfillmentOption
    productTags:
      description: product tags associated with the product
      type: array
      items:
        type:
        - string
        - 'null'
ProductSearchResponse:
  type: object
  additionalProperties: false
  description: |
    Result of a product search
  required:
  - products
  properties:
    products:
      type: array
      minItems: 1
      maxItems: 500
      items:
        $ref: '#/Product'
    problems:
      type: array
      items:
        $ref: ./_common.yml#/Problem
    _links:
      $ref: ./_common.yml#/Links
ProductSummary:
  type: object
  additionalProperties: false
  description: |
    Summary of the booking's underlining products.
  required:
  - id
  - description
  - code
  properties:
    id:
      type: string
    description:
      type: string
    code:
      type: string
ProductTag:
  description: "Values from the [Product Tags Code List](https://osdm.io/spec/catalog-of-code-lists/#ProductTags)\nKnown values:\n\
    - SPLIT_RESERVATION\n  Indicate for the provider that the distributor is prepared to get reservations including a split\
    \ inside the reservation\n  Without this indication the provider is not allowed to use the SplitSection Object inside\
    \ a reservation. \n  The implementation of SPLIT_RESERVATION is not recommended. To provide reservations that do not cover\
    \ a full leg \n  multiple reservations as offerParts should be created.\n- CARD_LOST\n  Tag used to request a non-trip\
    \ offer to replace a lost card. This applies to physical cards only.\n- TICKET_LOST\n  Tag used to request a non-trip\
    \ offer to replace a lost ticket. This applies to physical tickts only.\n- Product Types\n  All product types can be used\
    \ as Product Tags in the search\n"
  type: string
  x-extensible-enum:
  - SPLIT_RESERVATION
  - CARD_LOST
  - TICKET_LOST
  - ADMISSION_MULTI_RIDE
  - ADMISSION_POINT2POINT
  - ADMISSION_PASS
  - UPGRADE_PASS
  - UPGRADE_POINT2POINT
  - UPGRADE_MULTI_RIDE
  - RESERVATION
  - ANCILLARY_SERVICE
  - ANCILLARY_ITEM
  - REDUCTION_CARD
ProductTagGroup:
  description: |
    Group of product tags with a description.
  required:
  - code
  - description
  properties:
    code:
      type: string
      maxLength: 1024
    description:
      $ref: ./_common.yml#/Text
    productTags:
      type: array
      minItems: 1
      maxItems: 10000
      items:
        $ref: '#/ProductTag'
ProductTagName:
  description: |
    Product tags including a description,  The short text of the description should serve as a name on a button.
  required:
  - tag
  - description
  properties:
    tag:
      $ref: '#/ProductTag'
    description:
      $ref: ./_common.yml#/Text
ProductTagsResponse:
  type: object
  additionalProperties: false
  description: |
    Result of a product search
  required:
  - productTagNames
  - productTagGroups
  properties:
    productTagNames:
      type: array
      minItems: 1
      maxItems: 1000
      items:
        $ref: '#/ProductTagName'
    productTagGroups:
      type: array
      minItems: 1
      maxItems: 500
      items:
        $ref: '#/ProductTagGroup'
    problems:
      type: array
      items:
        $ref: ./_common.yml#/Problem
ProductType:
  description: |
    General product types harmonized across fare providers. (More to be added, use null for types not listed yet.)
    Values from the [Product Type Code List](https://osdm.io/spec/catalog-of-code-lists/#ProductTypes)
    Listed values here are examples.
  type: string
  x-extensible-enum:
  - ADMISSION_PASS
  - ADMISSION_MULTI_RIDE
  - ADMISSION_POINT2POINT
  - UPGRADE_PASS
  - UPGRADE_MULTI_RIDE
  - UPGRADE_POINT2POINT
  - RESERVATION
  - ANCILLARY_SERVICE
  - ANCILLARY_ITEM
  - REDUCTION_CARD
