<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Gtm" nsURI="platform:/resource/GTM%20data%20converter/model/gtm.xsd"
    nsPrefix="Gtm">
  <eClassifiers xsi:type="ecore:EClass" name="GTMTool">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conversionFromLegacy" lowerBound="1"
        eType="#//ConversionFromLegacy" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeLists" lowerBound="1"
        eType="#//CodeLists" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalTariffModel" lowerBound="1"
        eType="#//GeneralTariffModel" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeLists">
    <eStructuralFeatures xsi:type="ecore:EReference" name="carriers" eType="#//Carriers"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stations" eType="#//Stations"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="countries" eType="#//Countries"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="languages" eType="#//Languages"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currencies" eType="#//Currencies"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceBrands" eType="#//ServiceBrands"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nutsCodes" eType="#//NUTSCodes"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NUTSCodes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nutsCodes" upperBound="-1"
        eType="#//NutsCode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NutsCode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceBrands">
    <eOperations name="findServiceBRand" eType="#//ServiceBrand">
      <eParameters name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceBrands" upperBound="-1"
        eType="#//ServiceBrand" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceBrand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abbreviation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Countries">
    <eOperations name="findCountry" eType="#//Country">
      <eParameters name="codeUic" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="countries" upperBound="-1"
        eType="#//Country" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Country">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ISOcode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Languages">
    <eStructuralFeatures xsi:type="ecore:EReference" name="languages" upperBound="-1"
        eType="#//Language" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Language">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Currencies">
    <eOperations name="findCurrency" eType="#//Currency">
      <eParameters name="ISOcode" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currencies" upperBound="-1"
        eType="#//Currency" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Currency">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isoCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stations">
    <eOperations name="findStation" eType="#//Station">
      <eParameters name="countryCodeUIC" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
      <eParameters name="localCode" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    </eOperations>
    <eOperations name="findStation" eType="#//Station">
      <eParameters name="countryCodeUIC" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
      <eParameters name="localCode" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stations" upperBound="-1"
        eType="#//Station" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Station">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="country" eType="#//Country"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timetableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="borderStation" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameCaseUTF8" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameCaseASCII" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Carrier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Carriers">
    <eOperations name="findCarrier" eType="#//Carrier">
      <eParameters name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="carriers" upperBound="-1"
        eType="#//Carrier" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StationSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stations" upperBound="-1"
        eType="#//Station"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralTariffModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delivery" lowerBound="1"
        eType="#//Delivery" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fareStructure" lowerBound="1"
        eType="#//FareStructure" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Delivery">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="previousDeliveryId" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="replacedDeliveryId" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provider" eType="#//Carrier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemaVersion" eType="#//SchemaVersion"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acceptedSchemaVersion"
        eType="#//SchemaVersion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AfterSalesRules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="afterSalesRules" upperBound="-1"
        eType="#//AfterSalesRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AfterSalesRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" upperBound="-1"
        eType="#//AfterSalesCondition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AfterSalesCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transactionType" eType="#//AfterSalesTransactionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="individualContracts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="carrierFee" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fee" eType="#//Price"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicationTime" eType="#//ApplicationTime"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationTime" eSuperTypes="#//RelativeTime"/>
  <eClassifiers xsi:type="ecore:EClass" name="FareStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceClassDefinitions"
        eType="#//ServiceClassDefinitions" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceLevelDefinitions"
        eType="#//ServiceLevelDefinitions" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stationNames" eType="#//StationNames"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fareStationSetDefinitions"
        eType="#//FareStationSetDefinitions" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calendars" eType="#//Calendars"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="texts" eType="#//Texts"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reductionCards" eType="#//ReductionCards"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fareElements" eType="#//FareElements"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="combinationConstraints"
        eType="#//CombinationConstraints" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="salesAvailabilityConstraints"
        eType="#//SalesAvailabilityConstraints" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="travelValidityConstraints"
        eType="#//TravelValidityConstraints" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regionalConstraints" eType="#//RegionalConstraints"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionPoints" eType="#//ConnectionPoints"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="carrierConstraints" eType="#//CarrierConstraints"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceConstraints" eType="#//ServiceConstraints"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passengerConstraints" eType="#//PassengerConstraints"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reductionConstraints" eType="#//ReductionConstraints"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personalDataConstraints"
        eType="#//PersonalDataConstraints" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="afterSalesRules" eType="#//AfterSalesRules"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prices" eType="#//Prices"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fulfillmentConstraints"
        eType="#//FulfillmentConstraints" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reservationParameters"
        eType="#//ReservationParameters" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedOnlineServices"
        eType="#//SupportedOnlineServices" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fareResourceLocations"
        eType="#//FareResourceLocations" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionPoints">
    <eOperations name="findSimpleConnectionPoint" eType="#//ConnectionPoint">
      <eParameters name="station" eType="#//Station"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionPoints" upperBound="-1"
        eType="#//ConnectionPoint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LegacyBorderPointCode"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectedStationSets" upperBound="-1"
        eType="#//StationSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSource" eType="#//DataSource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameUtf8" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FareResourceLocations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trainResourceLocations"
        eType="#//TrainResourceLocations" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stationResourceLocations"
        eType="#//StationResourceLocations" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="carrierResourceLocations"
        eType="#//CarrierResourceLocations" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrainResourceLocations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trainResourceLocations"
        upperBound="-1" eType="#//TrainResourceLocation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StationResourceLocations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stationResourceLocations"
        upperBound="-1" eType="#//StationResourceLocation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CarrierResourceLocations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="carrierResourceLocations"
        upperBound="-1" eType="#//CarrierResourceLocation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrainResourceLocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="carrier" lowerBound="1"
        eType="#//Carrier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onlineResources" upperBound="-1"
        eType="#//OnlineResource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trainId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StationResourceLocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="onlineResources" upperBound="-1"
        eType="#//OnlineResource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stations" upperBound="-1"
        eType="#//Station"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionPoints" upperBound="-1"
        eType="#//ConnectionPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OnlineResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offerRequestType" eType="#//OfferRequestType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interfaceType" eType="#//InterfaceType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="system" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FulfillmentConstraints">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fulfillmentConstraints"
        upperBound="-1" eType="#//FulfillmentConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FulfillmentConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acceptedFulfilmentTypes"
        upperBound="-1" eType="#//FulfillmentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredControlDataExchange"
        upperBound="-1" eType="#//ControlDataExchangeTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="individualTicketingPermitted"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="acceptedBarcodes" eType="#//AcceptedBarcodes"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredBarcodes" eType="#//RequiredBarcodes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredBarcodes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredBarcodes" upperBound="-1"
        eType="#//BarcodeTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AcceptedBarcodes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acceptedBarcodes" upperBound="-1"
        eType="#//BarcodeTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupportedOnlineServices">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supportedOnlineServices"
        upperBound="-1" eType="#//OnlineServiceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StationNames">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stationName" upperBound="-1"
        eType="#//Station"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FareElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//FareType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//Text"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="price" eType="#//Price"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regionalConstraint" eType="#//RegionalConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceConstraint" eType="#//ServiceConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="carrierConstraint" eType="#//CarrierConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceClass" eType="#//ServiceClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceLevel" eType="#//ServiceLevel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="salesAvailability" eType="#//SalesAvailabilityConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="travelValidity" eType="#//TravelValidityConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="combinationConstraint"
        eType="#//CombinationConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fareDetailDescription"
        eType="#//Text"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacyAccountingIdentifier"
        eType="#//LegacyAccountingIdentifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personalDataConstraint"
        eType="#//PersonalDataConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reservationParameter" eType="#//ReservationParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reductionConstraint" eType="#//ReductionConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fulfillmentConstraint"
        eType="#//FulfillmentConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passengerConstraint" eType="#//PassengerConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="afterSalesRule" eType="#//AfterSalesRule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSource" eType="#//DataSource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FareStationSetDefinitions">
    <eOperations name="findFareSet" eType="#//FareStationSetDefinition">
      <eParameters name="carrier" eType="#//Carrier"/>
      <eParameters name="legacyCode" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fareStationSetDefinitions"
        upperBound="-1" eType="#//FareStationSetDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FareStationSetDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSource" eType="#//DataSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="carrier" eType="#//Carrier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="legacyCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameUtf8" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stations" upperBound="-1"
        eType="#//Station"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyAccountingIdentifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seriesId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tariffId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addSeriesId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReductionConstraints">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reductionConstraints" upperBound="-1"
        eType="#//ReductionConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FareElements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fareElements" upperBound="-1"
        eType="#//FareElement" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonalDataConstraints">
    <eStructuralFeatures xsi:type="ecore:EReference" name="personalDataConstraints"
        upperBound="-1" eType="#//PersonalDataConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonalDataConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredPersonalData" upperBound="-1"
        eType="#//RequiredPersonalData" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allowedChanges" upperBound="-1"
        eType="#//AllowedPersonalDataChanges" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredPersonalData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ticketHolderOnly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataItem" eType="#//PersonalDataItemsType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transfer" upperBound="-1"
        eType="#//PersonalDataTransferType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fulfillmentType" upperBound="-1"
        eType="#//FulfillmentType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="crossBorder" upperBound="-1"
        eType="#//CrossBorderCondition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllowedPersonalDataChanges">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acceptedReason" eType="#//PersonalDataChangeReason"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PassengerConstraints">
    <eStructuralFeatures xsi:type="ecore:EReference" name="passengerConstraints" upperBound="-1"
        eType="#//PassengerConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PassengerConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="travelerType" eType="#//TravelerType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//Text"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperAgeLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerAgeLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="travelAloneAgeLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reservationAgeLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAncilliary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerWeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxTotalPassengerWeight"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minTotalPassengerWeight"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includedFreePassengers"
        upperBound="-1" eType="#//IncludedFreePassengerLimit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="excludedPassengerCombinations"
        upperBound="-1" eType="#//PassengerCombinationConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PassengerCombinationConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerType" eType="#//TravelerType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncludedFreePassengerLimit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerType" eType="#//TravelerType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CombinationConstraints">
    <eStructuralFeatures xsi:type="ecore:EReference" name="combinationConstraints"
        upperBound="-1" eType="#//CombinationConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CombinationConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="combinationModels" upperBound="-1"
        eType="#//FareCombinationModel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TravelValidityConstraints">
    <eStructuralFeatures xsi:type="ecore:EReference" name="travelValidityConstraints"
        upperBound="-1" eType="#//TravelValidityConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TravelValidityConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validDays" eType="#//Calendar"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="travelDays" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" eType="#//ValidityRange"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnConstraint" eType="#//ReturnValidityConstraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="excludedTimeRange" upperBound="-1"
        eType="#//ExcludedTimeRange" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SalesAvailabilityConstraints">
    <eStructuralFeatures xsi:type="ecore:EReference" name="salesAvailabilityConstraints"
        upperBound="-1" eType="#//SalesAvailabilityConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SalesAvailabilityConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="restrictions" upperBound="-1"
        eType="#//SalesRestriction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSource" eType="#//DataSource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SalesRestriction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="salesDates" eType="#//Calendar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startOfSale" eType="#//StartOfSale"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endOfSale" eType="#//EndOfSale"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndOfSale" eSuperTypes="#//RelativeTime"/>
  <eClassifiers xsi:type="ecore:EClass" name="StartOfSale" eSuperTypes="#//RelativeTime"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReductionCards">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reductionCards" upperBound="-1"
        eType="#//ReductionCard" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReductionCard">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cardIssuer" lowerBound="1"
        eType="#//Carrier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Text"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceClasses" upperBound="-1"
        eType="#//ServiceClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idRequiredForBooking" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CarrierConstraints">
    <eStructuralFeatures xsi:type="ecore:EReference" name="carrierConstraints" upperBound="-1"
        eType="#//CarrierConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CarrierConstraint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="INCLUDE_OR_EXCLUDE"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includedCarriers" upperBound="-1"
        eType="#//Carrier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="excludedCarriers" upperBound="-1"
        eType="#//Carrier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceConstraints">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceConstraints" upperBound="-1"
        eType="#//ServiceConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceConstraint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="INCLUDE_OR_EXCLUDE"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includedServiceBrands"
        upperBound="-1" eType="#//ServiceBrand"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="excludedServiceBrands"
        upperBound="-1" eType="#//ServiceBrand"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegionalConstraints">
    <eStructuralFeatures xsi:type="ecore:EReference" name="regionalConstraints" upperBound="-1"
        eType="#//RegionalConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegionalConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryConnectionPoint" eType="#//ConnectionPoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exitConnectionPoint" eType="#//ConnectionPoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regionalValidity" upperBound="-1"
        eType="#//RegionalValidity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSource" eType="#//DataSource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegionalValidity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seqNb" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viaStation" eType="#//ViaStation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="zone" eType="#//Zone"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="line" eType="#//Line" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="polygone" eType="#//Polygone"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceLevelDefinitions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceLevelDefinition"
        upperBound="-1" eType="#//ServiceLevel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Texts">
    <eStructuralFeatures xsi:type="ecore:EReference" name="texts" upperBound="-1"
        eType="#//Text" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textUTF8" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textICAO" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortTextUTF8" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortTextICAO" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="translations" upperBound="-1"
        eType="#//Translation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Translation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="language" eType="#//Language"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textUTF8" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textICAO" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortTextUTF8" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortTextICAO" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Prices">
    <eStructuralFeatures xsi:type="ecore:EReference" name="prices" upperBound="-1"
        eType="#//Price" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Price">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currencies" upperBound="-1"
        eType="#//CurrencyPrice" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSource" eType="#//DataSource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VATDetail">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="country" lowerBound="1"
        eType="#//Country"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taxId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" eType="#//TaxScope"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CurrencyPrice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="currency" eType="#//Currency"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VATdetails" upperBound="-1"
        eType="#//VATDetail" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceClassDefinitions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceClassDefinitions"
        lowerBound="1" upperBound="-1" eType="#//ServiceClass" containment="true"
        resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Calendars">
    <eStructuralFeatures xsi:type="ecore:EReference" name="calendars" lowerBound="1"
        upperBound="-1" eType="#//Calendar" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Calendar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="untilDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="utcOffset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dates" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSource" eType="#//DataSource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReservationParameters">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reservationParameters"
        upperBound="-1" eType="#//ReservationParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReservationParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optionalReservation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params9181" eType="#//ReservationParams9181"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" eType="#//ReservationOptions"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReservationParams9181">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="travelClass" eType="#//ReservationTravelClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceLevel" eType="#//ReservationServiceLevel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="service" eType="#//ReservationService"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="berthType" eType="#//ReservationBerthType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coachType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="compartmentType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tariff" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReservationOptions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferences" upperBound="-1"
        eType="#//ReservationPreferenceGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceBrands" upperBound="-1"
        eType="#//ServiceBrand"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="graphicalReservation" eType="#//GraphicalReservationType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReservationPreferenceGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preference" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="group" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="#//ClassId"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classicClass" eType="#//ClassicClassType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//Text"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceLevel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" lowerBound="1" eType="#//Text"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="combiningServiceClasses"
        upperBound="-1" eType="#//ServiceClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reservationParameter" eType="#//ReservationParameter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includesClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeRange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" eType="#//TimeRangeScope"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="from" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="until" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExcludedTimeRange" eSuperTypes="#//TimeRange"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValidityRange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="#//TimeUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hoursAfterMidnight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelativeTime">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="#//TimeUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" eType="#//TimeReferenceType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnValidityConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="excludedWeekdays" upperBound="-1"
        eType="#//WeekDay"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latestReturn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="earliestReturn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViaStation">
    <eOperations name="getDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="station" eType="#//Station"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="carrier" eType="#//Carrier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="route" eType="#//Route"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternativeRoutes" upperBound="-1"
        eType="#//AlternativeRoute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fareStationSet" eType="#//FareStationSetDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlternativeRoute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stations" upperBound="-1"
        eType="#//ViaStation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Route">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stations" upperBound="-1"
        eType="#//ViaStation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Zone">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binaryZoneId" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Base64Binary"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zoneId" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="carrier" eType="#//Carrier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryStation" eType="#//Station"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="terminalStation" eType="#//Station"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nutsCode" eType="#//NutsCode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binaryZoneId" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Base64Binary"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineId" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="carrier" eType="#//Carrier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryStation" eType="#//Station"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="terminalStation" eType="#//Station"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nutsCode" eType="#//NutsCode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Polygone">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edge" upperBound="-1" eType="#//Edge"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="system" eType="#//GeoSystem"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eastWest" eType="#//HemisphereEW"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="northSouth" eType="#//HemisphereNS"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="#//GeoUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accuracy" eType="#//GeoUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CarrierResourceLocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="carrier" lowerBound="1"
        eType="#//Carrier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceBrand" eType="#//ServiceBrand"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onlineResources" upperBound="-1"
        eType="#//OnlineResource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CrossBorderCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromCountry" eType="#//Country"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toCountry" eType="#//Country"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedServiceBrands"
        upperBound="-1" eType="#//ServiceBrand"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FareCombinationModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" eType="#//CombinationModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="combinableCarriers" upperBound="-1"
        eType="#//Carrier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onlyWhenCombined" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allowedAllocators" upperBound="-1"
        eType="#//Carrier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceCluster" eType="#//Clusters"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowedClusters" upperBound="-1"
        eType="#//Clusters"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allowedCommonContracts"
        upperBound="-1" eType="#//Carrier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReductionConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredReductionCards"
        upperBound="-1" eType="#//RequiredReductionCard" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredReductionCard">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cardClass" eType="#//ServiceClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="card" lowerBound="1" eType="#//ReductionCard"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConversionFromLegacy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacy108" lowerBound="1"
        eType="#//Legacy108" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" lowerBound="1"
        eType="#//ConversionParams" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConversionParams">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TaxId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VATpercentage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="country" eType="#//Country"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacyBorderPointMappings"
        eType="#//LegacyBoderPointMappings" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacyStationMappings"
        eType="#//LegacyStationMappings" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacyTargetFares" eType="#//LegacyTargetFares"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacyFareStationMappings"
        eType="#//LegacyFareStationSetMappings" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacyStationToServiceBrandMappings"
        eType="#//LegacyStationToServiceConstraintMappings" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endOfSale" eType="#//EndOfSale"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="StartOfSale" eType="#//EndOfSale"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetFareTemplate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priceFactor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Float" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//FareType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//Text"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="price" eType="#//Price"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regionalConstraint" eType="#//RegionalConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceConstraint" eType="#//ServiceConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="carrierConstraint" eType="#//CarrierConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceClass" eType="#//ServiceClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceLevel" eType="#//ServiceLevel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="salesAvailability" eType="#//SalesAvailabilityConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="travelValidity" eType="#//TravelValidityConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="combinationConstraint"
        eType="#//CombinationConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fareDetailDescription"
        eType="#//Text"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacyAccountingIdentifier"
        eType="#//LegacyAccountingIdentifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personalDataConstraint"
        eType="#//PersonalDataConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reservationParameter" eType="#//ReservationParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reductionConstraint" eType="#//ReductionConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fulfillmentConstraint"
        eType="#//FulfillmentConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passengerConstraint" eType="#//PassengerConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="afterSalesRule" eType="#//AfterSalesRule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyStationToServiceConstraintMappings">
    <eOperations name="findServiceConstraint" eType="#//ServiceConstraint">
      <eParameters name="stationCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacyStationToServiceBrandMappings"
        upperBound="-1" eType="#//LegacyStationToServiceConstraintMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyStationToServiceConstraintMapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceConstraint" eType="#//ServiceConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyStationMappings">
    <eOperations name="findMappedStation" eType="#//Station">
      <eParameters name="stationcode" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stationMappings" upperBound="-1"
        eType="#//LegacyStationMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyStationMap">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="legacyCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="station" eType="#//Station"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyStation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyBoderPointMappings">
    <eOperations name="getMappingByBorderPointCode" eType="#//LegacyBorderPointMapping">
      <eParameters name="borderPointCode" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="borderPoints" upperBound="-1"
        eType="#//LegacyBorderPointMapping" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyBorderPointMapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="station" eType="#//Station"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionPoint" eType="#//ConnectionPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyFareStationSetMappings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacyFareStationSetMap"
        upperBound="-1" eType="#//LegacyFareStationSetMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyFareStationSetMap">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="legacyCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stationSet" eType="#//FareStationSetDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyFares">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fares" lowerBound="1" upperBound="-1"
        eType="#//LegacyFare" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyFare">
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" upperBound="5"
        eType="#//LegacyDescription" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Legacy108">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="characterSet" eType="#//CharacterSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacySeriesList" eType="#//LegacySeriesList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacyFares" eType="#//LegacyFares"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacyDistanceFares" eType="#//LegacyDistanceFares"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacyRouteFares" eType="#//LegacyRouteFares"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacyStations" eType="#//Legacy108Stations"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeZone" eType="#//TimeZone"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="carrier" eType="#//Carrier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Legacy108Stations">
    <eOperations name="findStation" eType="#//Legacy108Station">
      <eParameters name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    </eOperations>
    <eOperations name="findByBorderPoint" eType="#//Legacy108Station">
      <eParameters name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacyStations" upperBound="-1"
        eType="#//Legacy108Station" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Legacy108Station">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="borderPointCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameUTF8" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stationCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fareReferenceStationCode"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyRouteFares">
    <eStructuralFeatures xsi:type="ecore:EReference" name="routeFare" lowerBound="1"
        upperBound="-1" eType="#//LegacyRouteFare" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyRouteFare">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seriesNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fare2nd" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fare1st" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fareTableNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnFare1st" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnFare2nd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validUntil" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacySeries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="viastations" upperBound="-1"
        eType="#//LegacyViastation" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance1" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pricetype" lowerBound="1"
        eType="#//LegacyCalculationType" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validUntil" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pricing" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//LegacySeriesType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromStation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toStation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacySeriesList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="series" lowerBound="1"
        upperBound="-1" eType="#//LegacySeries" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyDistanceFares">
    <eStructuralFeatures xsi:type="ecore:EReference" name="distanceFare" lowerBound="1"
        upperBound="-1" eType="#//LegacyDistanceFare" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyDistanceFare">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fare2nd" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fare1st" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fareTableNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnFare1st" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnFare2nd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validUntil" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyViastation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyTargetFares">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetFares" lowerBound="1"
        upperBound="-1" eType="#//TargetFareTemplate" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AfterSalesTransactionType">
    <eLiterals name="REFUND" value="1"/>
    <eLiterals name="EXCHANGE" value="2"/>
    <eLiterals name="EXCHANGE_KEEP_CARRIER" value="3"/>
    <eLiterals name="EXCHANGE_CHANGE_CARRIER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BarcodeTypes">
    <eLiterals name="FCB" value="1"/>
    <eLiterals name="TLB" value="2"/>
    <eLiterals name="SSB" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ClassicClassType">
    <eLiterals name="FIRST" value="1"/>
    <eLiterals name="SECOND" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CharacterSet">
    <eLiterals name="LATIN1_ISO88591" value="1" literal="LATIN-1_ISO-8859-1"/>
    <eLiterals name="LATIN2_ISO88592" value="2" literal="LATIN-2_ISO-8859-2"/>
    <eLiterals name="LATINGREEK_ISO88595" value="3" literal="LATIN-GREEK_ISO-8859-5"/>
    <eLiterals name="RUSSIAN_KOI8R" value="4" literal="RUSSIAN_KOI8-R"/>
    <eLiterals name="USASCII" value="5"/>
    <eLiterals name="UKRAINIAN_KOI8U" value="6"/>
    <eLiterals name="LATIN4_ISO88594" value="7" literal="LATIN-4_ISO-8859-4"/>
    <eLiterals name="LATINKYRILLIC_ISO88595" value="8"/>
    <eLiterals name="LATIN5_ISO88599" value="9"/>
    <eLiterals name="LATIN7_ISO885913" value="10"/>
    <eLiterals name="LATIN9_ISO885915" value="11"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Clusters">
    <eLiterals name="BUSINESS"/>
    <eLiterals name="FULLFLEX" value="1"/>
    <eLiterals name="SEMIFLEX" value="2"/>
    <eLiterals name="NONFLEX" value="3"/>
    <eLiterals name="PROMO" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CombinationModel">
    <eLiterals name="SEPARATE_TICKET" value="1"/>
    <eLiterals name="SEPARATE_CONTRACT" value="2"/>
    <eLiterals name="CLUSTERING" value="3"/>
    <eLiterals name="COMBINING" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ControlDataExchangeTypes">
    <eLiterals name="IRS90918_4_PEER2PEER" value="2" literal="IRS90918_4_PEER2PEER"/>
    <eLiterals name="IRS90918_4_REGISTRY" value="1"/>
    <eLiterals name="PROPRIETARY" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FareType">
    <eLiterals name="NRT"/>
    <eLiterals name="IRT" value="1"/>
    <eLiterals name="RES" value="2"/>
    <eLiterals name="RPT" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FulfillmentType">
    <eLiterals name="SID" value="2"/>
    <eLiterals name="SIP" value="1"/>
    <eLiterals name="SIS" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GeoSystem">
    <eLiterals name="wgs84"/>
    <eLiterals name="grs80" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GeoUnit">
    <eLiterals name="microDegree"/>
    <eLiterals name="tenthmilliDegree" value="1"/>
    <eLiterals name="milliDegree" value="2"/>
    <eLiterals name="centiDegree" value="3"/>
    <eLiterals name="deciDegree" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GraphicalReservationType">
    <eLiterals name="IRS90918_1" value="1"/>
    <eLiterals name="GTM" value="2"/>
    <eLiterals name="NONE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HemisphereEW">
    <eLiterals name="EAST"/>
    <eLiterals name="WEST" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HemisphereNS">
    <eLiterals name="NORTH"/>
    <eLiterals name="SOUTH" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InterfaceType">
    <eLiterals name="IRS90918_1_RESERVATION_BINARY" value="1" literal="IRS90918_1_RESERVATION_BINARY"/>
    <eLiterals name="GTM" value="2"/>
    <eLiterals name="IRS90918_1_RESERVATION_XML" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LegacyCalculationType">
    <eLiterals name="distance_based" value="1"/>
    <eLiterals name="route_based" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LegacyPassengerType">
    <eLiterals name="ADULT" value="1"/>
    <eLiterals name="CHILD" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LegacySeriesType">
    <eLiterals name="border_destination" value="2"/>
    <eLiterals name="transit" value="1"/>
    <eLiterals name="station_station" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OfferRequestType">
    <eLiterals name="POINT2POINT" value="1"/>
    <eLiterals name="AREA" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OnlineServiceType">
    <eLiterals name="OFFER" value="1"/>
    <eLiterals name="BOOKING" value="2"/>
    <eLiterals name="RESERVATION_LEGACY_918_1" value="3"/>
    <eLiterals name="RESERVATION_PREF" value="4"/>
    <eLiterals name="RESERVATION_GRAPH" value="6"/>
    <eLiterals name="INCREASE" value="7"/>
    <eLiterals name="DECREASE" value="8"/>
    <eLiterals name="EXCHANGE" value="9"/>
    <eLiterals name="FULFILLMENT_ITEMS" value="10"/>
    <eLiterals name="FULFILLMENT" value="12"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PersonalDataItemsType">
    <eLiterals name="DATE_OF_BIRTH" value="1"/>
    <eLiterals name="E_MAIL" value="2"/>
    <eLiterals name="PHONE" value="3"/>
    <eLiterals name="FULL_NAME" value="4"/>
    <eLiterals name="LAST_NAME" value="5"/>
    <eLiterals name="LANGUAGE" value="6"/>
    <eLiterals name="TITLE" value="7"/>
    <eLiterals name="GENDER" value="8"/>
    <eLiterals name="DOC_TYPE" value="9"/>
    <eLiterals name="DOC_ID" value="10"/>
    <eLiterals name="DOC_NAME" value="11"/>
    <eLiterals name="DOC_CITY_OF_RESIDENCE" value="12"/>
    <eLiterals name="DOC_COUNTRY_OF_BIRTH" value="13"/>
    <eLiterals name="DOC_COUNTRY_OF_ISSUE" value="14"/>
    <eLiterals name="DOC_COUNTRY_OF_RESDENCE" value="15"/>
    <eLiterals name="DOC_DATE_OF_ISSUE" value="16"/>
    <eLiterals name="DOC_GENDER" value="17"/>
    <eLiterals name="DOC_NATIONALITY" value="18"/>
    <eLiterals name="DOC_LIMIT_OF_VALIDITY" value="19"/>
    <eLiterals name="DOC_CITY_OF_ISSUE" value="20"/>
    <eLiterals name="DOC_CITY_OF_BIRTH" value="21"/>
    <eLiterals name="DOC_TYPE_PASSPORT" value="22"/>
    <eLiterals name="CARD_ISSUER" value="23"/>
    <eLiterals name="CARD_NUMBER" value="24"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PersonalDataTransferType">
    <eLiterals name="SID" value="1"/>
    <eLiterals name="SIS_CONTROL" value="2"/>
    <eLiterals name="BOOKING" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PersonalDataChangeReason">
    <eLiterals name="IN_GENERAL" value="1"/>
    <eLiterals name="MARRIAGE" value="2"/>
    <eLiterals name="DOCUMENT_EXCHANGE" value="3"/>
    <eLiterals name="AGENT_ERROR" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReservationTravelClass">
    <eLiterals name="FIRST" value="1"/>
    <eLiterals name="SECOND" value="2"/>
    <eLiterals name="C" value="3"/>
    <eLiterals name="P" value="4"/>
    <eLiterals name="T" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReservationServiceLevel">
    <eLiterals name="A"/>
    <eLiterals name="B" value="1"/>
    <eLiterals name="AH" value="2"/>
    <eLiterals name="AM" value="3"/>
    <eLiterals name="AR" value="4"/>
    <eLiterals name="AS" value="5"/>
    <eLiterals name="AV" value="6"/>
    <eLiterals name="AW" value="7"/>
    <eLiterals name="BC" value="8"/>
    <eLiterals name="BD" value="9"/>
    <eLiterals name="BE" value="10"/>
    <eLiterals name="BH" value="11"/>
    <eLiterals name="BN" value="12"/>
    <eLiterals name="BR" value="13"/>
    <eLiterals name="BS" value="14"/>
    <eLiterals name="C" value="15"/>
    <eLiterals name="D" value="16"/>
    <eLiterals name="DR" value="17"/>
    <eLiterals name="D2" value="18"/>
    <eLiterals name="D4" value="19"/>
    <eLiterals name="D5" value="20"/>
    <eLiterals name="D6" value="21"/>
    <eLiterals name="E" value="22"/>
    <eLiterals name="EX" value="23"/>
    <eLiterals name="F" value="24"/>
    <eLiterals name="G" value="25"/>
    <eLiterals name="G2" value="26"/>
    <eLiterals name="H" value="27"/>
    <eLiterals name="K" value="28"/>
    <eLiterals name="L" value="29"/>
    <eLiterals name="M" value="30"/>
    <eLiterals name="N" value="31"/>
    <eLiterals name="O" value="32"/>
    <eLiterals name="O3" value="33"/>
    <eLiterals name="O4" value="34"/>
    <eLiterals name="O5" value="35"/>
    <eLiterals name="O8" value="36"/>
    <eLiterals name="OB" value="37"/>
    <eLiterals name="OL" value="38"/>
    <eLiterals name="OS" value="39"/>
    <eLiterals name="OT" value="40"/>
    <eLiterals name="P" value="41"/>
    <eLiterals name="Q" value="42"/>
    <eLiterals name="R" value="43"/>
    <eLiterals name="S" value="44"/>
    <eLiterals name="SL" value="45"/>
    <eLiterals name="T" value="46"/>
    <eLiterals name="TL" value="47"/>
    <eLiterals name="U" value="48"/>
    <eLiterals name="W" value="49"/>
    <eLiterals name="X" value="50"/>
    <eLiterals name="Y" value="51"/>
    <eLiterals name="Z" value="52"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReservationService">
    <eLiterals name="SEAT" value="1"/>
    <eLiterals name="COUCHETTE" value="2"/>
    <eLiterals name="BERTH" value="3"/>
    <eLiterals name="CAR_CARRIAGE" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReservationBerthType">
    <eLiterals name="SINGLE" value="1"/>
    <eLiterals name="SPECIAL" value="2"/>
    <eLiterals name="DOUBLE" value="3"/>
    <eLiterals name="T2" value="4"/>
    <eLiterals name="T3" value="5"/>
    <eLiterals name="T4" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SchemaVersion">
    <eLiterals name="V_1_0" value="1" literal="1.0"/>
    <eLiterals name="V_0_0" value="2" literal="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeZone">
    <eLiterals name="CET" value="1" literal="Central European Time"/>
    <eLiterals name="GMT" value="2" literal="Greenwich Mean Time"/>
    <eLiterals name="EET" value="3" literal="Eastern European Time"/>
    <eLiterals name="MST" value="4" literal="Moskow Standard Time"/>
    <eLiterals name="WET" value="5" literal="Western European Time"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TaxScope">
    <eLiterals name="INTERNALTIONAL" value="1"/>
    <eLiterals name="NATIONAL" value="2"/>
    <eLiterals name="SHORT_DISTANCE" value="3"/>
    <eLiterals name="LONG_DISTANCE" value="4"/>
    <eLiterals name="ANY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeReferenceType">
    <eLiterals name="BEFORE_DEPARTURE" value="1"/>
    <eLiterals name="AFTER_DEPARTURE" value="2"/>
    <eLiterals name="BEFORE_VALIDITY" value="3"/>
    <eLiterals name="BEFORE_START_VALIDITY" value="4"/>
    <eLiterals name="AFTER_END_VALIDITY" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeRangeScope">
    <eLiterals name="START_OF_TRAVEL" value="1"/>
    <eLiterals name="COMPLETE_RANGE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeUnit">
    <eLiterals name="DAY"/>
    <eLiterals name="HOUR" value="1"/>
    <eLiterals name="MINUTE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TravelerType">
    <eLiterals name="ADULT" value="1"/>
    <eLiterals name="CHILD" value="3"/>
    <eLiterals name="YOUTH" value="2"/>
    <eLiterals name="SENIOR" value="4"/>
    <eLiterals name="ACCOMP_PRM" value="5"/>
    <eLiterals name="DOG" value="20"/>
    <eLiterals name="LUGGAGE" value="21"/>
    <eLiterals name="ACCOMP_DOG" value="22"/>
    <eLiterals name="CAR" value="30"/>
    <eLiterals name="BICYCLE" value="31"/>
    <eLiterals name="MOTOCYCLE" value="32"/>
    <eLiterals name="TRAILER" value="33"/>
    <eLiterals name="GRAPHICAL_RES" value="40"/>
    <eLiterals name="OPT_RESERVATION" value="41"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WeekDay">
    <eLiterals name="MONDAY" value="1"/>
    <eLiterals name="TUESDAY" value="2"/>
    <eLiterals name="WEDNESDAY" value="3"/>
    <eLiterals name="THURSDAY" value="4"/>
    <eLiterals name="FRIDAY" value="5"/>
    <eLiterals name="SATURDAY" value="6"/>
    <eLiterals name="SUNDAY" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataSource">
    <eLiterals name="MANUAL" value="1"/>
    <eLiterals name="CONVERTED" value="2"/>
    <eLiterals name="IMPORTED" value="3"/>
    <eLiterals name="GENERATED" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ClassId">
    <eLiterals name="A" value="1"/>
    <eLiterals name="B" value="2"/>
    <eLiterals name="C" value="3"/>
    <eLiterals name="D" value="4"/>
  </eClassifiers>
</ecore:EPackage>
