type: object
additionalProperties: false
description: >
  product selection by product code or product tag for an offer request (exactly
  one of `productCode` and `productTag` must be provided). The number of items
  indicates the quantity 

  to be required. Passengers must be referenced in case the product is intended
  for passengers.
properties:
  productCode:
    type: string
    examples:
      - PT00AD
  productTag:
    type: string
  numberOfItmes:
    type:
      - integer
      - 'null'
    format: int32
    minimum: 1
  externalPassengerRefs:
    type: array
    items:
      type: string
