type: object
additionalProperties: false
description: >
  Validity depending on boarding / leaving of a train. The ticket is valid

  from departure until the destination station in the train if departure or
  destination is within the from - until range.

  The validation can reference the departure or the destination time to decide
  the validity (e.g. Eurail/Interrail passes

  currently use the departure for the validity on night trains).
required:
  - from
  - until
  - carriers
  - scope
properties:
  from:
    type: string
    format: date-time
  until:
    type: string
    format: date-time
  carriers:
    type: array
    items:
      $ref: ./CompanyRef.yml
    minItems: 1
  excludedServiceBrands:
    type: array
    items:
      $ref: ./ServiceBrandCode.yml
  includedServiceBrands:
    type: array
    items:
      $ref: ./ServiceBrandCode.yml
  scope:
    $ref: ./TrainValidityScope.yml
