import type { InjectionKey } from 'vue'
import type { paths } from '@/schemas/schema' // generated by openapi-typescript
import type { Client } from 'openapi-fetch'

export const osdmClientKey: InjectionKey<Client<paths>> = Symbol('osdm')
export const requestorHeaderKey: InjectionKey<string> = Symbol('RequestorHeader')
