@startuml

title "BookingPart State Model"

state onhold #LightGreen

state refunded #LightBlue
state released #LightBlue
state exchangeOngoing #LightBlue
state exchanged #LightBlue

[*] --> prebooked : POST /bookings with offer ids, optional accommodation / ancillariy ids
prebooked --> confirmed: POST /bookings/{id}/fulfillments \n where at least 1 fulfillment is confirmed
prebooked --> [*]: DELETE /bookings/{id}
prebooked --> [*]: ttl reached
prebooked --> error: unrecoverable error \nat confirmation/fulfillment
prebooked --> fulfilled: POST /bookings/{id}/fulfillments \n where all fulfillments are fulfilled
prebooked --> onhold: PATCH /bookings/{id}/onhold-offer

onhold --> confirmed: PATCH /bookings/{id}/fulfillments
onhold --> cancelled: extended ttl reached
onhold --> error: onrecoverable error 

confirmed --> fulfilled: PATCH /bookings/{id}/fulfillments \n all fulfillments are now fulfilled
confirmed --> error: unrecoverable error at fulfillment \n of a confirmed booking

fulfilled --> refunded: POST /bookings/{id}/refundOffers \n followed by confirm
fulfilled --> exchangeOngoing: POST /exchangeOffers \n followed by confirm
fulfilled --> released: POST /bookings/{id}/releaseOffers \n followed by confirm
fulfilled --> [*] : archiving

cancelled --> [*]

refunded --> [*]

exchangeOngoing --> exchanged: POST /bookings/{id}/exchangeOperations \n followed by POST /booking/{id}/fulfillments
exchangeOngoing --> fulfilled: exchange is not finalized

exchanged --> [*]

released --> refunded: If refund operation is triggered
released --> [*]

error --> [*] : DELETE /booking \nin a cleanup context
error --> [*] : archiving

@enduml