@startuml
[*] --> prebooked : POST /bookings with offer ids, optional accommodation / ancillariy ids

prebooked --> confirmed: POST /bookings/{id}/fulfillments \n where at least 1 fulfillment is confirmed
prebooked --> [*]: DELETE /bookings/{id}
prebooked --> [*]: ticket-time-limit reached
prebooked --> error: unrecoverable error \nat confirmation/fulfillment
prebooked --> fulfilled: POST /bookings/{id}/fulfillments \n where all fulfillments are fulfilled
confirmed --> fulfilled: PATCH /bookings/{id}/fulfillments \n all fulfillments are now fulfilled
confirmed --> error: unrecoverable error at fulfillment \n of a confirmed booking
fulfilled --> [*] : archiving
error --> [*] : DELETE /booking \nin a cleanup context
error --> [*] : archiving
@enduml