@startuml
[*] --> prebooked: PATCH /Bookings/id {exchangeOfferId}
prebooked --> confirmed: POST /Bookings/id/fulfillments \n where at least 1 fulfillment in the exchange is confirmed
prebooked --> [*]: DELETE /Bookings/id/ExchangeOperation/id
prebooked --> [*]: ExchangeOperation TicketTimeLimit reached
prebooked --> error: unrecoverable error at fulfillment < of a prebooked exchangeOperation
confirmed --> fulfilled: PATCH /bookings/id/fulfillments \n <all fulfillments are now fulfilled>
confirmed --> error: unrecoverable error at fulfillment \n <of a confirmed exchangeOperation>
confirmed --> [*] : archiving
fulfilled --> [*] : archiving
error --> [*] : archiving
@enduml