title: Places Data Model

class Place <<R,Orchid>> #linen {
  id: string
  name: string
}

class Address <<D, Green>> #linen {
  addressName
  countryName
}

class PointOfInterest <<D, Green>> #linen {
  pointOfInterestCode
  pointOfInterestName
}

class StopPlace <<D, Green>> #linen {
  stopPlaceRef
  stopPlaceName
}

class FareConnectionPoint <<D, Green>> #linen {
  stopPlace: StopPlace []
}

class GeoPosition <<D, Green>> #linen {
  longitude
  latitude
}

Place -- "address" Address
Place -- "pointOfInterest" PointOfInterest
Place -- "stopPlace" StopPlace
Place -- "fareConnection" FareConnectionPoint
Place -- "geoPosition" GeoPosition
