@startuml

title "Refund State Model"

[*] --> proposed: POST /bookings/id/refundOffers
proposed--> confirmed: PATCH /bookings/id/refundOffers
proposed--> [*] : DELETE /bookings/id/refundOffers\n OR refundOffer expiry
confirmed --> [*] : archiving

@enduml