@startuml

title "Trip State Model"

[*] --> planned
[*] --> confirmed
planned --> confirmed
confirmed --> changed: delay
confirmed --> cancelled: disruption
confirmed --> [*]
cancelled --> [*]
changed --> cancelled: disruption
changed --> [*] 

@enduml