@startuml
hide footbox

actor "TicketVendor"
control "Time"

"TicketVendor" -> "Distributor": POST compensation claim

"Distributor" -> "Distributor": validate claim

"Distributor" --> "TicketVendor": Bank account missing

"TicketVendor" -> "Distributor": PATCH compensation claim

"Distributor" -> "Distributor": retrieve the booking, select the affected carriers/fare providers

"Distributor" -> "Carrier:C1": post a new compensation claim

"Distributor" -> "Carrier:C2": post a new compensation claim

"Carrier:C2" -> "Carrier:C2": decide claim

"Carrier:C2" --> "Distributor": claim changed

"Time" --> "Distributor": approaching legal deadline for claim

"Distributor" -> "Carrier:C2": get claim

"Distributor" -> "Distributor": decide on the claim

"Distributor" -> "Carrier:C1": patch claim with decision and amount

"Distributor" --> "TicketVendor": claim changed

"TicketVendor" -> "Distributor": GET compensation claim

@enduml