hide footbox

actor Retailer

== Add offers to an existing bookedOffer ==

Retailer -> Distributor: POST /bookings/5678/booked-offers/12345/additional-offers
Distributor --> Retailer: Offers


Retailer --> Distributor: /bookings/5678/booked-offers/12345/reservations{BookedOfferReservationRequest}
Distributor --> Retailer: bookedOffers
Retailer --> Distributor: /bookings/5678/booked-offers/12345/ancillaries{BookedOfferAncillarieRequest}
Distributor --> Retailer: bookedOffers

Retailer -> Distributor: PATCH /bookings/5678 <setting the fulfillmentOptions>
Distributor --> Retailer: <Booking resource with updated fulfillmentOptions>

Retailer -> Distributor: POST /bookings/{bookingId}/fulfillments
Distributor --> Retailer: {fulfillments}



