
hide footbox

actor Retailer 

== Cancelling a release offer ==
Retailer -> Distributor: GET /bookings/5678
Distributor --> Retailer: <Booking>
Retailer -> Distributor: DELETE /bookings/5678/releaseOffers/23
loop for each fulfillment in the relase offer
    alt FareProvider supports release offers 
      Distributor -> FareProvider: cancel release offer
	  FareProvider --> Distributor : OK
   
    end
end
Distributor --> Retailer: 200 OK