hide footbox

actor Retailer

== Creating the offers collection & getting the initial set of trips ==
Retailer -> Distributor: POST /offers <MUNCHEN-PARIS, 23/10/2021, 2 pax, dob, ...>
Distributor -> JourneyPlanner : <retrieve trips information based on API Consumer request>
JourneyPlanner --> Distributor : <trips information>
Distributor -> Distributor: determine FareProvider for each segment
Distributor -> Distributor : create offer requests
Distributor -> FareProvider1: get offers 
FareProvider1 --> Distributor : request with trips
Distributor -> FareProvider2: get offers 
FareProvider2 --> Distributor : request with trips
Distributor -> Distributor : reconcile trips and \nconstruct global offers
Distributor --> Retailer: <List of Offers>

== Creating a booking based on one of the received offers ==
Retailer -> Distributor: POST /bookings/ <offerId= 8765>
Distributor -> Distributor : create local booking 5678
Distributor -> FareProvider1: provisionally book offerpart1 
FareProvider1 --> Distributor : OK response (can vary per FareProvider)
Distributor -> Distributor : add FareProvider booking to local booking
Distributor -> FareProvider2: provisionally book offerpart2 
FareProvider2 --> Distributor : NOK response (can vary per FareProvider)

Distributor -> FareProvider1: DELETE /Bookings/5678
FareProvider1 --> Distributor : OK response (can vary per FareProvider)

== respond to API Consumer with an error message ==
Distributor --> Retailer: 400 NOK (JSon Problem object)