hide footbox

actor Retailer

== Searching for places, to be used to import master data ==
Retailer -> Distributor: GET /places/
Distributor --> Retailer: <Places List>

== Retrieving one specific place resource ==
Retailer -> Distributor: GET /places/12345
Distributor --> Retailer: <Place 12345>