@startuml
hide footbox

actor Retailer

== Requesting an exchange for the two known passengers ==
Retailer -> Distributor: POST /exchange-offers <MUNCHEN-PARIS, 25/10/2021, pax1, pax2, fulfilment1, fulfilment2, ...>
Distributor --> Retailer: <List of Exchange-Offers>

== Retrieving a specific exchange Offer ==
Retailer -> Distributor: GET /exchange-offers/5678
Distributor --> Retailer: <Exchange-offer 5678>
Retailer -> Distributor: GET /offers/4321"
Distributor --> Retailer: <offer 4321>

== Checking for additional required passenger information==
Retailer -> Retailer: check offer RequestedInformation 

== Provisional exchange  including seat selection options and required additional pax info ==
Retailer -> Distributor: PATCH /bookings/ <exchangeOfferId= 4321, pax1 <loyaltyCard>, res1 <window>>
Distributor -> Distributor : create \nexchangeOperation 1 \nin booking 5678
Distributor --> Retailer: <Updated Booking 5678, now with a prebooked exchangeOperation 89, and updated passengers>

== Setting fulfillment type for the exchange ==
Retailer -> Distributor: PATCH /bookings/5678/exchangeOperations/89 <setting the fulfillmentOptions>
Distributor --> Retailer: <ExchangeOperation 89 resource with updated fulfillmentOptions>

== Confirming the exchange & triggering fulfillment ==
Retailer -> Distributor: POST /bookings/5678/fulfillments
Distributor --> Retailer: <Fulfillments created in the booking 5678>
@enduml