hide footbox

actor Retailer

== Creating a refund offer ==
Retailer -> Distributor: GET /Bookings/5678
Distributor --> Retailer: <Booking>
Retailer -> Distributor: POST /Bookings/5678/refundOffers <tickets to be refunded,  optionally overrule code>
loop for each fulfillment in the refund offer request
    alt FareProvider supports refund offers 
      Distributor -> FareProvider: request refund offer
	  FareProvider --> Distributor : refund offer
    else refund only supports direct refund
      Distributor -> Distributor: calculate refund offer
    end
end
Distributor --> Retailer: <RefundOffer for the provided tickets or passengers>