hide footbox

actor Retailer 

== Creating the trip collection & getting the initial set of trips ==
Retailer -> Distributor: POST /trips-collection <MUNCHEN-PARIS, 23/10/2021>
Distributor -> Journey_Planner : <retrieve trips information based on API Consumer request>
Journey_Planner --> Distributor : <trips information>
Distributor --> Retailer: <Trips-Collection with list of Trip Refs & scrolling tokens>

== Scrolling to the (chronologically) next set of trips in the collection  ==
Retailer -> Distributor: GET /trips-collection/2345?page="next"
Distributor -> Journey_Planner : <retrieve trips information based on page OR computed new params>
Journey_Planner --> Distributor : <trips information>
Distributor --> Retailer: <Trips-Collection with list of Trip Refs & scrolling tokens>
