@startuml
hide footbox

actor "TicketVendor"


"TicketVendor" -> "Distributor": POST compensation claim

"Distributor" -> "Distributor": validate claim

"Distributor" --> "TicketVendor": Bank account missing

"TicketVendor" -> "Distributor": PATCH compensation claim

"Distributor" -> "Distributor": retrieve the booking, select the affected carriers/fare providers

"Distributor" -> "Carrier:C1": post a new compensation claim

"Distributor" -> "Carrier:C2": post a new compensation claim

"Carrier:C2" -> "Carrier:C2": decide claim

"Carrier:C2" --> "Distributor": claim changed

"Carrier:C1" -> "Carrier:C1": decide claim

"Carrier:C1" --> "Distributor": claim changed

"Distributor" -> "Carrier:C1": get claim

"Distributor" -> "Carrier:C2": get claim

"Distributor" -> "Distributor": combine decisions

"Distributor" --> "TicketVendor": claim changed

"TicketVendor" -> "Distributor": GET compensation claim

@enduml