hide footbox

actor Retailer 

== setting additional passenger information that may be required to confirm the booking, starting from the booking overview ==
Retailer -> Distributor: GET /bookings/5678
Distributor --> Retailer: <Booking with booked offers and passengers resources>
Retailer -> Retailer: check booking RequestedInformation
Retailer -> Distributor: PATCH /bookings/5678/passengers/123/ < additional information for passenger>
loop for each offerPart in bookedOffers
    Distributor -> FareProvider: update passenger data 
	FareProvider --> Distributor : OK response (can vary per FareProvider)
end
Distributor -> Distributor : update local booking
Distributor --> Retailer: <passenger updated with the added information>

== setting fulfillment type for the booking ==
Retailer -> Distributor: GET /bookings/5678
Distributor --> Retailer: <Booking with only references to embedded resources>
Retailer -> Distributor: PATCH /bookings/5678 <setting the fulfillmentOptions>
Distributor --> Retailer: <Booking resource with updated fulfillmentOptions>