hide footbox

actor Retailer 

== Cancelling a refund offer ==
Retailer -> Distributor: GET /bookings/5678
Distributor --> Retailer: <Booking>
Retailer -> Distributor: DELETE /bookings/5678/refundOffers/23
loop for each fulfillment in the refund offer request
    alt FareProvider supports refund offers 
      Distributor -> FareProvider: cancel refund offer
	  FareProvider --> Distributor : OK
   
    end
end
Distributor --> Retailer: 200 OK