hide footbox

actor API_Consumer 

== Retrieving an offer & setting seat selection options, starting with tripoffer overview==
API_Consumer -> OSDM_Provider: GET /Trips-offers/5678?embed="TRIPOFFERS, TRIPOFFERS.TRIPS,TRIPOFFERS.OFFERS, TRIPOFFERS.OFFERS.OFFERPARTS TRIPOFFERS.PASSENGERS"
OSDM_Provider --> API_Consumer: <Trip-offer with the Trip resource, offers & its offerparts, passengers>
API_Consumer -> OSDM_Provider: PATCH /Offers/8765/reservations/7654/ < reservation with selectedPlaces or selectedOptions set with desired seating option>
OSDM_Provider --> API_Consumer: <updated reservation with desired reservation>

== Retrieving an offer & setting seat selection options, starting with selected offer ==
API_Consumer -> OSDM_Provider: GET /offers/8765?embed="OFFERS.OFFERPARTS"
OSDM_Provider --> API_Consumer: <offer with its offerparts>
API_Consumer -> OSDM_Provider: PATCH /Offers/8765/reservations/7654/ < reservation with selectedPlaces or selectedOptions set with desired seating option>
OSDM_Provider --> API_Consumer: <updated reservation with desired reservation>

== setting additional passenger information that may be required for provisional booking, starting from the tripoffer overview ==
API_Consumer -> OSDM_Provider: GET /Trips-offers/5678?embed="TRIPOFFERS, TRIPOFFERS.TRIPS,TRIPOFFERS.OFFERS, TRIPOFFERS.OFFERS.OFFERPARTS TRIPOFFERS.PASSENGERS"
OSDM_Provider --> API_Consumer: <Trip-offer with Trip resource, offers & its offerparts, passengers>
API_Consumer -> API_Consumer: check offer RequestedInformation
API_Consumer -> OSDM_Provider: PATCH /Offers/8765/passengers/123/ < additional information for passenger>
OSDM_Provider --> API_Consumer: <passenger updated with the added information>

== setting additional passenger information that may be required for provisional booking, starting from the offer for multiple passengers==
API_Consumer -> OSDM_Provider: GET /offers/8765?embed="OFFERS.OFFERPARTS"
OSDM_Provider --> API_Consumer: <offer with its offerparts>
API_Consumer -> API_Consumer: check offer RequestedInformation
API_Consumer -> OSDM_Provider: GET /Trips-offers/5678?embed="TRIPOFFERS.PASSENGERS"
loop for each passenger
  API_Consumer -> OSDM_Provider: GET /offers/8765/passengers/123
  OSDM_Provider --> API_Consumer: <passenger to be updated>
  OSDM_Provider --> API_Consumer: <passenger updated with the added information>
API_Consumer -> OSDM_Provider: PATCH /Offers/8765/passengers/123/ <additional information for passenger>
end