hide footbox

actor Retailer 

== setting additional passenger information that may be required to confirm the booking, starting from the booking overview ==
Retailer -> Distributor: GET /Bookings/5678?embed="BOOKING_BOOKEDOFFERS"
Distributor --> Retailer: <Booking with booked offers>
Retailer -> Distributor: DELETE /Bookings/5678
loop for each offerPart or FareProvider booking in bookedOffers
    Distributor -> FareProvider: cancel booking 
	FareProvider --> Distributor : OK response (can vary per FareProvider)
end
Distributor --> Retailer: 200 OK