hide footbox

actor Retailer 

== Creating a booking based on one or more offer(s) ==
Retailer -> Distributor: POST /bookings/ <offerId(s) of selected offer(s),\n selected optional reservation(s)/ancilliaries>
Distributor -> Distributor : create local booking 
loop for each offerPart in selected offer and optional offerpart
    Distributor -> FareProvider: provisionally book offerpart 
	FareProvider -> FareProvider: create FareProvider booking
	FareProvider --> Distributor : OK response (can vary per FareProvider)
	Distributor -> Distributor : add FareProvider booking to local booking
end
Distributor --> Retailer: <Created Booking>
