@startuml
hide footbox

actor "TicketVendor"

"TicketVendor" -> "Distributor": GET reduction cards

"TicketVendor" -> "Distributor": GET coach layouts

"TicketVendor" -> "Distributor": POST offers collection using from / to places

"Distributor" -> "Distributor": split the request to carriers / fare prooviders

"Distributor" -> "Carrier:C1": POST offers collection including trip 

"Distributor" -> "Carrier:C2": POST offers collection including trip 

"Distributor" -> "Distributor": combine fare offers according to fare rules

"Distributor" --> "TicketVendor": offers

"TicketVendor" -> "TicketVendor": manage customer selection of an offer

"TicketVendor" -> "Distributor": GET place-map (reservationId)
 
"Distributor" -> "Carrier:C1": GET place-map (reservationId)

"TicketVendor" -> "TicketVendor": combine place-maps with coach layouts and manage customer selection of a place

"TicketVendor" -> "Distributor": POST bookingid, place selection

"Distributor" -> "Carrier:C1": POST bookingid, place selection 

"Distributor" -> "Carrier:C2": POST booking 

"Distributor" --> "TicketVendor": booking  

"TicketVendor" -> "Distributor": POST fulfillments

"Distributor" -> "Carrier:C1": POST fulfillments

"Distributor" -> "Carrier:C2": POST fulfillments

"TicketVendor" <-- "Distributor": fulfillmentIds

loop for each fulfillment

"TicketVendor" -> "Distributor": GET fulfillmentId

end

@enduml