hide footbox

actor Retailer

== Confirm a refund offer ==
Retailer -> Distributor: GET /bookings/5678
Distributor --> Retailer: <Booking>
Retailer -> Distributor: PATCH /bookings/5678/refundOffers/23 <setting statuts to confirmed
loop for each fulfillment in the refund offer request
      Distributor -> FareProvider: apply refund
	  FareProvider --> Distributor : OK
	  Distributor -> Distributor : update local status
end
alt all fulfillments cancelled or refunded
    Distributor -> Distributor : update global booking status
end
Distributor --> Retailer: 200 OK