hide footbox

actor Retailer

== setting fulfillment type for the booking ==
Retailer -> Distributor: POST /bookings/5678/fulfillments
loop for each offerPart  bookedOffers
    Distributor -> FareProvider: fulfill booking 
	FareProvider --> Distributor : OK response (can vary per FareProvider)
end
Distributor --> Retailer: <Fulfillments created in the booking>