hide footbox

actor Customer

Customer -> Retailer: get an offer A to C
Retailer -> "Distributor 1": get an offer A to C

"Distributor 1" -> "Distributor 1": split trip into Distributor
"Distributor 1" -> "FareProvider 1": get a fare A to B
note right: B can be a virtual border point
"FareProvider 1" --> "Distributor 1": fare for A to B
"Distributor 1" -> "Distributor 2": forward offer request for B to C

"Distributor 2" -> "FareProvider 2": get a fare B to C
"FareProvider 2" --> "Distributor 2": fare for B to C
"Distributor 2" -> "Distributor 2": create offer part
"Distributor 2" --> "Distributor 1": offerPart

"Distributor 1" -> "Distributor 1": create offerPart from fares
"Distributor 1" -> "Distributor 1": create offer from offerParts
"Distributor 1" --> Retailer: offer

Retailer -> Retailer: create overall offer
Retailer --> Customer: overall offfer