post:
  tags:
    - Product
    - Search
  summary: Search for products based on search parameters.
  operationId: searchProducts
  parameters:
    - $ref: ../components/parameters/requestor.yml
    - $ref: ../components/parameters/acceptLanguage.yml
    - $ref: ../components/parameters/traceParent.yml
    - $ref: ../components/parameters/traceState.yml
    - $ref: ../components/parameters/acceptNamespace.yml
    - $ref: ../components/parameters/page.yml
  requestBody:
    required: true
    content:
      application/vnd.uic.osdm+json:
        schema:
          $ref: ../components/schemas/ProductSearchRequest.yml
  responses:
    '200':
      description: |
        booking search results found
      content:
        application/vnd.uic.osdm+json:
          schema:
            $ref: ../components/schemas/ProductSearchResponse.yml
      headers:
        Content-Language:
          schema:
            type: string
            description: >
              The language of translatable strings in the response (see
              RFC2616-sec14.12).
    '400':
      $ref: ../components/responses/BadRequestResponse.yml
    '401':
      $ref: ../components/responses/UnauthorizedResponse.yml
    '403':
      $ref: ../components/responses/ForbiddenResponse.yml
    '404':
      $ref: ../components/responses/NotFoundResponse.yml
    '415':
      $ref: ../components/responses/UnsupportedMediaTypeResponse.yml
    '500':
      $ref: ../components/responses/InternalServerErrorResponse.yml
    '501':
      $ref: ../components/responses/NotImplementedResponse.yml
    '503':
      $ref: ../components/responses/ServiceUnavailableResponse.yml
    default:
      $ref: ../components/responses/DefaultErrorResponse.yml
  security:
    - oAuth2ClientCredentials: []
